### ISSUE TITLE
Bandstructure

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#100]
Dear Dr. Shankar,

I have been following the tutorial in jDFT on plotting the band structure of graphene. I can plot the bandstructure using gnuplot.  May I know how to extract the raw data from the **bandstruct.eigenvals** file?
I have tried a few software to open it but not successful.

Thanks

**Comment by shankar1729** [comment]
It is a raw binary file with all band eigenvalues stored as double precision numbers, which you shoud be able to read in most analysis environments. For example, in python with numpy, you can do:

     E = np.fromfile('bandstruct.eigenvals').reshape((-1, nBands))
     plt.plot(E)

where nBands is the number of bands you specified in elec-n-bands.

Best,
Shankar

**Comment by moyulyy** [comment]
Dear Dr. Shankar,

The following python code is used
#  E = np.fromfile('bandstruct.eigenvals').reshape((-1, nbands)) 
#  np.savetxt("bandstruct_data.csv", E, fmt = '%f', delimiter = ',')
The output bandstruct_data.csv file shows twice as many rows as "kpoints" and columns as nbands,
I don't know if there are two band structures for up and down spin states, 
or if there are graph data points that require every two points in the graph to draw a straight line.

In my calculations, I set 15 kpoints, along with "Gamma" 0, "M" 5, "K" 9, "Gamma" 14, and nbands=368
The output bandstruct_data.csv file shows 30 rows and 368 columns, 
what should I do with this data so that I can draw the right  band structures  image in Origin.

Thank you again for your generous contribution to my issue.

**Comment by shankar1729** [comment]
If you have a spin-polarized calculation, reshape the energies as (2, -1, nbands). Then, you can plot the up and down spin band structures separately or overlaid as needed. (If you need a CSV, you can then output E[0] and E[1] separately to bandstruct_up.csv and bandstruct_dn.csv respectively.)

Best,
Shankar
