### ISSUE TITLE
about .Moments

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#107]
Dear Shankar,
In the foregoning question you said that "The latest commit fixes the dipole moment issues. (Note that the new code will explicitly set dipole moments in periodic directions to zero since this is not the Berry-phase implementation that can account for polarization lattices of periodic systems.)"
But I still get the .Moments with the following data after I replace the files of comands and electronic in /home/software/JDFTx-1.5/jdftx-1.5.0/jdftx
Electron moment of order 1: 86.154254	56.108827	2447.538067
Ion moment of order 1: -376.472066	-242.024489	-4942.276004
Total moment of order 1: -290.317813	-185.915661	-2494.737937
I wonder that I did something wrong. I installed the jdftx-1.5.0 a few months ago, and download the last jdftx-master three days ago after I saw your answers. I only replace the  comands and electronic in /home/software/JDFTx-1.5/jdftx-1.5.0/jdftx with the newest files without  reinstalling the jdftx-1.5.0, then I get these information. 
Could youp please point out where my operation is wrong ? How can I get the .Moment as you said?

Best
Anna

**Comment by shankar1729** [comment]
Please compile the code with the master archive. Just replacing a fraction of the source files without recompiling won't change anything. Also, very likely, if you only traced a fraction of the files, the code won't compile due to interdependent changes elsewhere. I would recommend replacing the entire source directory before recompiling, it doing a fresh build.

Best,
Shankar
