### ISSUE TITLE
difference between electronic-SCF and electronic-minimize

### ISSUE THREAD

**Issue by DaisyWang20** [shankar1729/jdftx#113]
Dear Dr Shankar,
i used to use electronic-minimize as the criteria whether the electronic step conveged. But I read the tutorial and found all examples used unly one key word:electronic-SCF; instand I use 

> electronic-minimize \
    nIterations 1000 \
    energyDiffThreshold 1e-6 

> 
And I found in a example

> Note that we have used the robust, but slower, minimization algorithm instead of SCF because the SCF algorithm does not reliably converge in fixed-potential mode (yet) due to a charge-sloshing instability between the system and the electron 

> reservoir.

Does that mean minimization algorithm is more reliable and can be used in any situation(vacuum calculations,solvations,target mu), while SCF algorithm can do all (because it's more quick)but target-mu?

Thanks!

**Comment by DaisyWang20** [comment]
And another question which puzzled me for a long time ,in the tutorial it says:

> V_SHE = - (mu - mu_SHE)

There is an overall negative sign due to differences in sign convention for electrode (reduction) potentials and electron chemical potentials. Experimentally, mu_SHE is calibrated to -4.44 eV. Alternately, we can calibrate mu_SHE by comparig theoretical calculations of the PZC of various metal surfaces against experimental measurements. We will use this approach, as it tends to cancel systematic errors in the solvation model. For the CANDLE solvation model, mu_SHE = -4.66 eV (from the CANDLE paper).

> 
So if I use CANDLE model in my calculations, I should set mu_SHE=-4.66eV. If in my situation
 U=-1 V vs RHE , pH in experiment is 7, thus 
U=-1-0.059*7=-1.42 V vs SHE, thus 
mu=-(U-U_SHE)/27.2114=-(-1.42-(-4.66)/27.2114=-0.1191 Hartree. 

Am I right?

Great thanks!

**Comment by DaisyWang20** [comment]
Sorry to interrupt you again! When I calculate dos calculations, I always get many vertical lines instand of smooth curves shown in the DOS example. What may be the reason? 
![image](https://user-images.githubusercontent.com/53133202/79060308-1bc4dd00-7cb6-11ea-8912-c5b389d13e20.png)

Great thanks!Hope you are in good health

**Comment by shankar1729** [comment]
Hi Daisy,

Yes, you are right about SCF vs minimize. In general, try the SCF for a test system from what you are trying to do. If it converges well, it will likely be somewhat faster. If you have SCF issues, you can fall back to minimize. It might also be a good idea to try both at the start of exploring a particular set of systems to determine which is faster for it.

The mu calculations look correct. Note that picking the calibration in the solvation model papers based on PZC of metal surfaces in one opinion (ours!) of what is the best practice to minimize systematic errors. It is also common practice to use a single consistent number based on the experiment (eg. 4.44 eV and 4.28 eV depending on who you ask) regardless of the solvation model. Neither of these is right or wrong: as I mentioned, our suggestion is based on cancelling systematic error from the solvation model in the dipole layer at the liquid interface.

Finally, as for your DOS: is that for a molecule / supercell with no k-point sampling? You get a bunch of lines like this then because the tetrahedron method then yields an array of delta functions at each KS eigenvalue. Use the Esigma parameter (try ~ 0.001 Eh) in DOS to combine them all into a smooth curve. You can adjust Esigma to trade off between smoothness and energy resolution of the curve.

Best,
Shankar

**Comment by DaisyWang20** [comment]
That works! Thank you very much !
