### ISSUE TITLE
DFT+U Tutorial

### ISSUE THREAD

**Issue by JamesPCrosby** [shankar1729/jdftx#124]
I am currently working through the tutorial on the JDFTx website.  I am trying to do the last exercise in the DFT+U where it asks you to calculate the band structure for FeO.  I have managed to produce files of PBE+U.n_up and PBE+U.n_dn.  I have also managed to generate the k-point file using the given script. 

However, when I run the band structure program from the tutorial on "Band Structure" I find I get the error:
"Reading n from file PBE+U.n ... Could not open PBE+U.n for reading"  I am unsure how to get the program to accept both .n files.

Thanks 
James

**Comment by shankar1729** [comment]
It looks like you don't have 'spintype z-spin' set in the band structure input file (or common.in if you set it up that way) . OCndequenty it is trying to read a single .n instead of .n_up and .n_dn.

After you get through this part, you will also need to modify the bandstruct.plot file to handle the two spin channels. Specifically modify the nRows line to:

```
nk = real(system("awk '$1==\"kpoint\" {nRows++} END {print nRows}' bandstruct.kpoints"))
nRows = nk*2
```

and then if you want to overlay the up and down spin bands in the same region, modify the plot command to:

```
set xrange [0:nk]
plot mu lt 0, \
	for [i=1:nCols] "bandstruct.eigenvals" binary format=formatString u ( $0  ):i w l lt 1 title (i==1 ? "Up" : ""), \
	for [i=1:nCols] "bandstruct.eigenvals" binary format=formatString u ($0-nk):i w l lt 2 title (i==1 ? "Dn" : "")
```

You can also leave the plot command unmodified, and it will plot the two spin channels next to each other, and you may want to update the x-labels.
