### ISSUE TITLE
energy descrepancy

### ISSUE THREAD

**Issue by KwonSnow** [shankar1729/jdftx#125]
Dear Shankar,

I'm running IrO2 calculation for electrochemistry.
My current job (single point) didn't converge, but I found something strange when I compared the final F in the electronic iteration (-2237.507245643412716) and the final output energy (-2237.5079750314339435).
There is ~ 0.02 eV difference. I wondering if there are independent definitions for these two free energies.
Any help will be greatly appreciated!
[Charged.zip](https://github.com/shankar1729/jdftx/files/4842814/Charged.zip)

Sincerely,
Soonho

**Comment by shankar1729** [comment]
Hi Soonho,

Those two energies should indeed be the same. This might stem from the poor convergence. There is a unitary transformation to the eigenbasis after the iterative part before the final energy evaluation, and this can reveal such a discrepancy due to incomplete convergence (thought it rarely happens).

300 SCF iterations is on the high side: maybe try electronic-minimize instead for this system? Also, unrelated note: you should be able to accelerate your run by using up to 10 processes. At least, 2 processes with 16 threads each may be a better use of 32 cores than a single process with 32 threads.

Best,
Shankar

**Comment by KwonSnow** [comment]
Dear, Shankar.
Yes, indeed, it only occurs when the calculation is yet converged. It explains clearly.
Thank you for your tip for the acceleration and minimization. I will try to find the optimal # of tasks for this system.
I appreciate it a lot!

Sincerely,
Soonho

**Comment by KwonSnow** [comment]
Dear prof. Shankar.

As I know, DFT inherently involves the scf. But then, I'm wondering why there are two separate tags in input file. The electronic-minimize and electronic-scf tags.
I want to know the difference between these two tags and How should I differentiate the final values from each method.

Sincerely,
Soonho

**Comment by shankar1729** [comment]
Hi Soonho,

SCF is only one algorithmic strategy for solving the KS equations, an dmost
codes only have SCF.

The variational minimize is a separate algorithm that directly minimizes
the total free energy as a function of the KS orbitals, without an inner
eigenvalue solve + outer SCF loop. Please see the cited theory papers (eg.
the Software X ones for details and further references.)

Best,
Shankar

**Comment by KwonSnow** [comment]
Dear Shankar.
The paper says variational minimization is essential for many solvated systems. And, indeed, it is so valid for my calculation, too.
Thank you for the explanation.
Sincerely,
Soonho
