### ISSUE TITLE
Wannier guesses do not cover desired subspace

### ISSUE THREAD

**Issue by agf58** [shankar1729/jdftx#133]
Hello,

I'm running a DoS calculation with a Pd slab using Wannier interpolation. I consistently get the following error message:
**Trial orbitals are linearly dependent / do not cover desired subspace at k = [ 0 0 0 ]**
Before I post my input file and a picture of the band structure, I'd like to understand what this message means, and what might it be an indication of in general.

Thanks in advance!

**Comment by shankar1729** [comment]
It means that the wavefunctions in the energy range of interest cannot be expressed as linear combinations of your trial orbitals, which is necessary for initializing the wannier functions. It could be caused by an input error such as accidentally specifying the same orbital more than once, or because some orbitals you chose are orthogonal to the wavefunctions in the relevant energy range. The latter could happen accidentally if some of the atomic trial orbitals happen to be semi-core ones, but you intended to specify the valence ones that are actually in the energy range of interest.

Best,
Shankar
