### ISSUE TITLE
Carry out the NEB calculation under fix-potential

### ISSUE THREAD

**Issue by 20190111** [shankar1729/jdftx#135]
Dear shankar,
I know that JDFTx could connect to the ASE interface with NEB and MD calculations, I can carry out some simple calculations using ASE with JDFTx calculator, but I cannot output the jdftx calculated result file to the specified location, the results are always in the /tmp file, Could you give me some advice ?
Can I carry out the NEB calculation under fix-potential with jdftx ? If it can be done, can you give me some scripts or examples for reference ?

Best,
Anna

**Comment by shankar1729** [comment]
Hi Anna,

You will need to edit the ASE interface code in the jdftx/scripts/ase directory to not delete the temporary directories if you want to keep this output. Comment out line 111 and put either pass or return there for the clean function.

I don't have an example for this specifically, but see in the ASE JDFTx tutorial how command elec-cutoff is passed through. You can use the same syntax to pass in a dict of any jdftx commands and corresponding arguments through. So that should allow you to do pretty much any jdftx calculation including fixed-potential ones through ASE. I have not tested fixed-potential NEB though, so I'm not sure if other problems emerge in trying to do so.

Best,
Shankar

**Comment by 20190111** [comment]
Hi Shankar,
Thanks for your reply. 
But I have another problem about the differential capacitance of Ag(100). I read your paper named "Evaluating continuum solvation models for the electrode-electrolyte interface: Challenges and strategies for improvement" on J. Chem. Phys. 146, 084111 (2017), the surface charge vs electrode potential under different continuum solvent models is shown as Fig.1 .
![图片](https://user-images.githubusercontent.com/46814723/91539983-c0397a00-e94c-11ea-8633-92e462d57421.png)
From the picture we can see that the curve is continuous with the CANDLE, I also test the slab for Ag(100), but the result is different showing in the follow picture
![图片](https://user-images.githubusercontent.com/46814723/91541101-620d9680-e94e-11ea-8acb-be3983468370.png), the surface charge drops abruptly about -0.1V (vs PZC). 
Here is my input file, please correct me if I do something wrong ?
[charge.in.txt](https://github.com/shankar1729/jdftx/files/5141824/charge.in.txt)

I think  it may  not be because of my parameters setting, because the abruptly drop not only happened on Ag(100), it's happened all the other metals I test. I want to know why this case happen ?  What should I do if I want to get the  differential capacitance of different metals with jdftx software ?

Best 
Anna

**Comment by shankar1729** [comment]
Hi Anna,

This behavior is an unfortunate consequence of CANDLE's charge asymmetry correction, which happens to end up depending on the cell size for charged surface calculations. So the jump in capacitance is present in your curve and the one in that paper, but with different magnitudes. See [J. Chem. Phys. 148, 144105 (2018)](https://aip.scitation.org/doi/10.1063/1.5024219) (and its SI) for a discussion of this. 

Best,
Shankar
