### ISSUE TITLE
Cohesive energy of Li

### ISSUE THREAD

**Issue by panxiang126** [shankar1729/jdftx#138]
Dear Dr. Shankar,

I used JDFTx to calculate the cohesive energy of Li as `ELi_coh = ELi_bulk/2 - ELi_single`, where `ELi_bulk` (-5.53 Ha, see attached `jdftxOutFile_Li_bulk.out`) and `ELi_single` (-2.61 Ha, see attached `jdftxOutFile_Li_single.out`) are the energy of the Li bulk and isolated Li atom, respectively. Accordingly, the calculated value is -3.87 eV, which is obviously far from the theoretical value (1.63 eV, see Kittle, C. Introduction to Solid State Physics. 2005, 8th Edition, John Wiely & Sons, Inc.). Do you have any ideas for this?

Best,
Pan

[Li_coh.zip](https://github.com/shankar1729/jdftx/files/5286783/Li_coh.zip)

**Comment by shankar1729** [comment]
Hi Pan,

You have done a calculation of Boron instead of Lithium, both for the BCC bulk and the individual atom. 

Additionally, for the atom you should set a non-zero spin state with elec-initial-magnetization in order to get to the correct spin configuration eventually. You don't need to get this exactly right in the beginning, but it is good to set it to what you expect based on the number of unpaired electrons.

Also note that the sign of the cohesive energy even for you calculation is positive: a positive cohesive energy corresponds to a lower total energy of the bulk compared to the individual atoms put together.

Best,
Shankar
