### ISSUE TITLE
electron-scattering

### ISSUE THREAD

**Issue by AmyJcc** [shankar1729/jdftx#139]
Dear Shankar,

Recently, I encountered a difficulty in calculating electron-electron scattering: due to the long calculation time of scattering, I tried to calculate the scattering rate of the partially K points. But there are some errors when setting the specific K points coordinate in the input file, so I have the following three confusions:
1. Is the idea of just calculating the scattering rate at the specified K point feasible?
2. If possible, how to set the parameters in the input file?

I look forward to your reply.

The following is  input file :
*********************scatter.in***************************************
lattice face-centered Cubic 7.65
ion-species SG15/$ID_ONCV_PBE.upf
elec-cutoff 30
ion Al 0 0 0 0
 
dump End Kpoints
dump-name scatter.$VAR

kpoint 0.0000000 0.0000000 0.0000000 
kpoint 0.0000000 0.0000000 0.0625000
kpoint 0.0000000 0.0000000 0.1250000
kpoint 0.0000000 0.0000000 0.1875000 
kpoint 0.0000000 0.0000000 0.2500000 
kpoint 0.0000000 0.0000000 0.3125000 

elec-n-bands 16
elec-smearing Fermi 0.01  #Set fillings using Fermi function at T = 0.01 Hartrees
electronic-SCF
converge-empty-states yes   #Make sure that empty state eigenvalues are reliable

coulomb-interaction Periodic
electron-scattering \
         eta 0.003675    \
         slabResponse no\
         Ecut 7.3

************the error message of output***********
Initialized 1 species with 1 total atoms.
Specified kpoint weights do not add to 1
End date and time: Tue Oct  6 09:58:01 2020  (Duration: 0-0:00:00.12)
Failed.

Best,
Amy

**Comment by shankar1729** [comment]
Hi Amy,

You cannot calculate specific k points separately because electron scattering involves all pairs k-points since an electron can change its k when it scatters against another.

I just pushed a commit that allows continuing an electron-scattering calculation. At the simplest, you can just run the job again and it will pick up from the last momentum transfer that was completed. 

You could also use a computeRange parameter to select a particular range of momentum transfers to run in a particular job, so that you could split up the overall calculation into many pieces run in parallel.

`electron-scattering ... computeRange 1 10`
`electron-scattering ... computeRange 11 20`

etc. with all other parameters and the input file remaining the same.

In the end, run electron-scattering again without computeRange, and you will get the usual final result. The new code will output partial results from each momentum transfer, which you can remove once you have collected the results together.

Best,
Shankar
