### ISSUE TITLE
coulomb-interaction under solvation model and constant potential

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#146]
Dear Shankar,
When I do slab (like Pt) calculation under solvation model and constant potential, I notice the guide use the commands
 "coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0" 
in the input file of your website, I wonder whether it will affect the effect of  solvation model or not, after all, these commands truncate coulomb interaction along the Z direction, and maybe it will have some impact on the interactions between the implicit solvation model and slab?

Best,
Leyu

**Comment by shankar1729** [comment]
Hi Leyu,

At present, when using solvation models, coulomb-truncation in embed mode doubles the size of the box used for computing the solvation model, but does not truncate the Coulomb kernels for other technical reasons. It relies instead on screening by the liquid and/or ions to minimize interaction between periodic images.

Note that, fundamentally, there is no reason we cannot use truncated Coulomb kernels with solvation models. If done correctly, this will eliminate the interactions between the slab and fluid bound charge in one cell with the periodic images of both of those along the truncated direction. We don't do it yet because this would require rearranging the way the solvation model energy / gradients are computed to be in terms of the fluid bound charge alone, and there are some complications in doing this generally and reliably for all solvation models (linear, nonlinear, nonlocal etc.). Additionally, we find the liquid screening takes care of minimizing image interactions on its own quite well, so this is not really necessary either.

Best,
Shankar
