### ISSUE TITLE
can't read wave-function in vibration run

### ISSUE THREAD

**Issue by maofeng** [shankar1729/jdftx#15]
Dear Ravishankar

I am running a calculation with molecular adsorbed on surface, meet a error (below) in read wave function ("vacuum.wfns") during the vibration calculation. But this wave function was read successfully during fluid calculation (Classical DFT).The input files of vacuum, vibration, and fluid are enclosed (changed to .txt).

Error: 
---------- Allocating electronic variables ----------
Initializing wave functions:  reading from 'vacuum.wfns'
Length of 'vacuum.wfns' was 8922471456 instead of the expected 14275816048 bytes.
Hint: Did you specify the correct nBandsOld, EcutOld and kdepOld?

Thank you
BR
maofeng 

[vacuumin.txt](https://github.com/shankar1729/jdftx/files/1417675/vacuumin.txt)
[vibrationin.txt](https://github.com/shankar1729/jdftx/files/1417676/vibrationin.txt)
[cdftin.txt](https://github.com/shankar1729/jdftx/files/1417677/cdftin.txt)

**Comment by shankar1729** [comment]
Hi Maofeng,

When you run vibrations, symmetries need to be disabled to support perturbations of atoms.  If you have k-point folding in your system, then this changes the reduced k-mesh set compared to the calculation without vibrations and makes the wavefunctions incompatible.

You have the following options:

* Disable symmetries throughout in the total energy / geometry optimization calculation:  not recommended because this will be much more expensive at all steps.

* Don't read the wavefunctions in the vibration calculation, and have it re-perform the minimization without symmetries.  This will still use symmetries to optimize the force matrix calculation, so this is far preferable.  (You should still converge the ionic positions separately.)

* Use the phonon code instead: this correctly handles k-point folding changes, and can also allow you to do supercell sampling and true free energy calculations.  For the 1x1x1 supercell, the outputs should be comparable to vibrations.

Thanks for pointing out this issue; I see that this is not mentioned in the documentation of the vibrations command; I will add that and try to make the error message more helpful.

Best,
Shankar

**Comment by shankar1729** [comment]
Improved error message and documentation update pushed to git now.

Best,
Shankar
