### ISSUE TITLE
JDFx 1.6 crashing while performing fixed-potential charged calculations with ClassicalDFT or non-aqueous solvents

### ISSUE THREAD

**Issue by arnabkabiraj** [shankar1729/jdftx#154]
Hi,
I've been trying to perform fixed potential calculations to explore the capacitive response of graphene and other 2D materials (as shown in http://jdftx.org/FixedPotential.html). This works out pretty well with fluid linearPCM-CANDLE/SalSA with H2O as a solvent. However, the calculations crash whenever I try to use any non-aqueous solvent (like EC or DMC with linearPCM-CANDLE/SalSA) or the ClassicalDFT fluid method (with H2O). This consistently happens with other 2D materials as well. I've also tried this in different machines (CPU only, Pascal Quadro P5000 GPU, Turing Quadro RTX 5000 GPU, Volta Tesla V100 GPU) with both cpu-only and gpu applications but the problem persists. Altering the pseudopotential (GBRV/SG15) doesn't work as well.
For instance, in the machine with 4 Pascal Quadro P5000 GPUs, I've used the following configuration command :  cmake -D EnableMKL=yes -D ForceFFTW=yes -D EnableLibXC=yes -D CompileNative=yes -D EnableCUDA=yes -D PinnedHostMemory=yes -D CudaAwareMPI=yes -D CUDA_ARCH=compute_61 -D CUDA_CODE=sm_61 ../jdftx. Similar configurations with relevant changes have been used for the other machines.
I've attached two example run directories with the relevant input and output files for your kind perusal.  
Please look into this issue.

https://indianinstituteofscience-my.sharepoint.com/:u:/g/personal/kabiraj_iisc_ac_in/EXGunYFVw_NIvUoAK2Rm6wYBetkfxK_t9mEox6n5HfQukQ?e=39VgON
https://indianinstituteofscience-my.sharepoint.com/:u:/g/personal/kabiraj_iisc_ac_in/ESvLSMKXebZLklnP0i7JTTYBAjM0g2QqqUuU0sEnH88Lqg?e=pTZ3MC

**Comment by shankar1729** [comment]
Hi Arnab,

Thank you for the detailed error report. Part of your error (eg. for ClassicalDFT or NonlinearPCM, any solvent) appears to be the bug that was recently fixed in commit [d1924c82](https://github.com/shankar1729/jdftx/commit/d1924c82e62a57ed5945705e9075739786b018bd). Please update and confirm here that it gets resolved.

The remaining errors could be due to the fact that CANDLE and SaLSA require specific solvent molecule details that are only available for the solvents they were parameterized for. Specifically, CANDLE was parameterized only for water and acetonitrile, while SaLSA was parameterized for water, CCL4 and chloroform. The code should not crash / seg-fault: I will look into that, but regardless the results will not be valid for EC, DMC etc. in those models. The parameters for EC and DMC were set only for the default GLSSA13 LinearPCM by Deniz Gunceler (see [this paper](https://doi.org/10.1088/0965-0393/25/1/015004) for details).

Best,
Shankar
