### ISSUE TITLE
"CUDA Error: invalid argument" after LCAO Initialization

### ISSUE THREAD

**Issue by shk11** [shankar1729/jdftx#159]
Dear Shankar,

I currently have an issue with calculations using the "electronic-minimize" tag: The calculation aborts directly after the LCAO initialisation. Starting the same calculation with the "electronic-scf" tag eliminates the problem. Furthermore, I only face the problem in cases where "electronic-minimize" is used in combination with "fluid-solve-frequency Inner". Please find attached the stack trace and the corresponding log file. Do you have an explanation for why this error occurs? 
[jdftx.log](https://github.com/shankar1729/jdftx/files/6309618/jdftx.log)
[jdftx-stacktrace.zip](https://github.com/shankar1729/jdftx/files/6309621/jdftx-stacktrace.zip)

Used versions:
jDFTx 1.6.0 (git hash (1d101425 and de1aa367) in combination with icc 18.0.5, openMPI 4.0, MKL2018, CUDA 11.0 and gcc8/9, openMPI 4.0, MKL2018, CUDA 11.0.

**Comment by shankar1729** [comment]
Hi Daniel,

I am unable to reproduce this crash with input extracted from your log file. I checked specifically with the most recent git version (1d10142) using CUDA 11 and gcc 9.3. As far as I can see, the only difference was running on a K80 GPU instead of a V100.

Does this happen reproducibly while running on the GPU? Does it happen only on the GPU? Could you get the same issue with a much smaller slab containing the same atom combinations and solvation?

Best,
Shankar

**Comment by shk11** [comment]
Hello Shankar,

Thank you very much for the feedback. I have contacted our system administrators, and it seems to be an issue with the memory allocation in the case of multiple active jobs on the GPU nodes. The problem has been fixed, and the calculations are working properly now. Thanks for the help and sorry for all the trouble.

Best wishes,
Daniel

**Comment by shankar1729** [comment]
Okay, that's great to hear: otherwise such bugs can be quite hard to track down! Thanks for the update.

Best,
Shankar
