### ISSUE TITLE
Solvents implemented and model compatibility

### ISSUE THREAD

**Issue by davidwaroquiers** [shankar1729/jdftx#160]
Dear all,

I was trying to use the CANDLE solvation model with EC and it failed to work (free energy was nan). I am guessing it has to do with which solvents are calibrated for said model (same calculation works with H2O). My question is then, is there a way to know which models can be used for a given fluid-solvent ? At this stage, I am mainly interested in EC and DMC but I would like to know also if it is easily extendable to other solvents. Also, I was wondering about the anions and cations, what would be the procedure to define other types of anions and cations (e.g. Li+ and PF6-).

Thanks a lot,

David

**Comment by shankar1729** [comment]
Hi David,

Indeed, CANDLE has not been parameterized for EC or DMC, only for water and acetonitrile (per the original paper). When the code initializes the solvation model (you can do this in dry-run mode), it will print a warning if the selected model has not been parameterized for the chosen solvent. (We chose to make this a warning instead of an error because once could presumably set appropriate parameters using pcm-params; this is what we would do while parameterizing the model.)

At the moment, EC and DMC are only available in GLSSA13 based on a [paper by Gunceler and Arias](https://arxiv.org/abs/1403.6465). For most continuum solvation models, there is no point in defining different ion types, because they are all effectively point charges that are non-adsorbing; just use Na+ and F- as in the tutorials. Only SaLSA and ClassicalDFT actually use any details of the ions beyond their charge and concentration.

Best,
Shankar

**Comment by davidwaroquiers** [comment]
Dear Shankar,


Thank you very much for your rapid answer. That makes it much clearer. I'll then use GLSSA at this stage.


Best,

David
