### ISSUE TITLE
PBE0 pseudopotentials

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#161]
Opium can generate PBE0 pseudopotentials in the FHI format. Is it possible to use those in JDFTx to speed up calculations with hybrid functionals?

**Comment by shankar1729** [comment]
Yes, JDFTx supports FHI pseudopotentials natively. In fact, OPIUM/FHI pseudopotentials were the original format we used before supporting UPF and USPP. 

However, the change in pseudopotential will not speed up hybrid functional calculations unless you are somehow able to design one that works at much lower energy cutoffs / reduces the number of shells included as valence.

Best,
Shankar

**Comment by sergbuto** [comment]
I guess, if I use the Opium's FHI file with PBE0 pseudopotential, the 'elec-ex-corr hyb-PBE0' is not needed in the JDFTx input.  Is that right?

**Comment by shankar1729** [comment]
No, that's not right. You will need to specify which functional to use explicitly; it is not picked up automatically from the PSP.

Energy cutoff is controlled by elec-cutoff and the default is 20 Eh. It is not controlled by the functional: the pseudopotential determines what would be an appropriate cutoff. Once again, this is not automatic on purpose: some pseudopotentials state recommended cutoffs, but we often find that these are not reliable and one needs to converge with cutoff.

Best,
Shankar

**Comment by sergbuto** [comment]
If I have to use the 'elec-ex-corr hyb-PBE0' command in any case, what difference it would really make to specify the PBE or PBE0 pseudopotential file in 'ion-species' in terms of the JDFTx work?

**Comment by shankar1729** [comment]
Well, the treatment of XC within the atom during generation of the PSP would be different: this would lead to (slightly) different orbital eigenvalues, eigenvectors and projectors. It is more consistent to use pseudopotential generated with same XC functional as the plane-wave calculation, eg. LDA ps with LDA calculations etc. However, due to poor availability of hybrid functional pseudopotentials, people often end up doing hybrid calculations with PBE pseudopotentials.

Best,
Shankar
