### ISSUE TITLE
fixed-potential calculations

### ISSUE THREAD

**Issue by SoonhoKwon0312** [shankar1729/jdftx#17]
Dear Ravishankar,

I want to calculate a single-point calculation of Pt slab model with adsorbates at fixed-potential.
Since I want to calculate from 0.0 V (SHE) to 1.3 V (SHE), so I constructed my script file, like below.

for iMu in {0..13}; do
    export mu="$(echo $iMu | awk '{printf("%.4f", -0.17125+0.1*$1/27.2114)}')"

I used the calibrated standard hydrogen electrode of -4.66 eV because I'm using CANDLE. (JCP, 142, 064107)

But all the calculations from the que scripts were stopped in the middle of electronic minimization.
I can't interpret "jdftx-stacktrace". Could you please take a look into it?
[archive.zip](https://github.com/shankar1729/jdftx/files/1595118/archive.zip)

Thank you!
Happy New Year!

Soonho

**Comment by abhiShandy** [comment]
Hi Soonho,

I think there is a mistake in your formula:   -0.17125+0.1*$1/27.2114
You should use negative sign.

In [documentation](http://jdftx.org/CommandTargetMu.html), the formula is **mu = -(Vref + V)/27.2114**

**Comment by shankar1729** [comment]
Hi Soonho,

Abhishek is right about the sign, but the stack trace seems to be a separate issue.  This seems to be a seg fault in MKL resulting from not freeing internal buffers; it only happened in very specific versions of MKL.

If I remember correctly, this could be rectified by compiling against the serial version of MKL and let JDFTx do the threading (instead of the default which links to the threaded version of MKL). To do this, include the CMake option "-D ThreadedBLAS=no"  when configuring. Also use "-D ForceFFTW=yes" to make sure you are not using MKL FFTs, which also have been buggy for me in the past.

Please let me know if that helps!

Best,
Shankar

**Comment by SoonhoKwon0312** [comment]
AbhiShandy! I corrected the line so that I get positive potential compared to 0.0 V vs SHE.

Shankar! I will do it and let you know the results!

Thank you, all!

**Comment by SoonhoKwon0312** [comment]
I installed a new fftw with -fPIC in CFLAG since the error was like below:
"/usr/bin/ld: /usr/local/lib/libfftw3.a(alloc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC"
And it works even I don't use options including StaticLinking, ThreadedBLAS and ForceFFTW.
Thank you, Shankar!

**Comment by shankar1729** [comment]
Glad to hear it worked!
