### ISSUE TITLE
jDFTx stopped when using coulomb-interaction Isolated

### ISSUE THREAD

**Issue by zhichao-1699** [shankar1729/jdftx#171]
Hi, Shankar,
I am currently testing a large molecular system using jDFTx. But when I was trying to use the coulomb-interaction Isolated tag, jDFTx seemed to crush somehow. Error message shows like this:
![truncate](https://user-images.githubusercontent.com/67491987/121140364-56031d80-c86c-11eb-8de9-484ec34d052b.png)

But when I turned off this tag, calculations seem to be smooth. So what is wrong here? Input/output files and jdftx-stacktrace file treating with the script are as follows.
[jdftx-error.zip](https://github.com/shankar1729/jdftx/files/6614269/jdftx-error.zip)

Thanks,
Zhichao

**Comment by shankar1729** [comment]
Hi Zhichao,

My best guess is that it is a memory error due to the incorrect parallelization of this job: you have only 2 kpoints*spins (nStates), so you should run with at most 2 processes. Rerun this with the equivalent of "mpirun -n 2 jdftx -c24 ..." to use the two nodes with two processes and 24 threads per process to use all the cores still.

In your current version, you are having to reproduce large memory objects such as the truncated kernel on each process, which is likely leading to a memory overflow.

Best,
Shankar
