### ISSUE TITLE
lattice-minimize command does not optimize ion positions

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#172]
As the title says, the lattice-minimize command does not optimize/change the ion positions and the 'Forces in Lattice coordinates' equal to zeros in the output file.

The input file:

include common.in
kpoint-folding 8 8 8

spintype spin-orbit
add-U U f 0.073499
elec-smearing Fermi 0.01
electronic-SCF energyDiffThreshold 1e-8 \ 
   residualThreshold 1e-07 eigDiffThreshold 1e-8 nIterations 300

lattice-minimize nIterations 10

dump-name Lattice-min.$VAR
dump Ionic State

The common.in file:

#Save the following to common.in:
lattice \
     9.37493130396727      0.00000000000000      0.00000000000000 \
     0.00000000000000      9.37493130396727      0.00000000000000 \
     0.00000000000000      0.00000000000000      9.37493130396727

ion-species $ID_ONCV_PBE-smb_r.upf
ion-species $ID_ONCV_PBE_fr.upf
elec-cutoff 40

ion U   0.000000000000000   0.000000000000000   0.000000000000000 1
ion U   0.000000000000000   0.500000000000000   0.500000000000000 1
ion U   0.500000000000000   0.000000000000000   0.500000000000000 1
ion U   0.500000000000000   0.500000000000000   0.000000000000000 1
ion C   0.500000000000000   0.500000000000000   0.500000000000000 1
ion C   0.500000000000000   0.000000000000000   0.000000000000000 1
ion C   0.000000000000000   0.500000000000000   0.000000000000000 1
ion C   0.000000000000000   0.000000000000000   0.500000000000000 1

**Comment by shankar1729** [comment]
There are no free internal coordinates in this crystal: all ionic positions are fully constrained by space group symmetries. Consequently, the forces after symmetrization turn out to be exactly zero and there is no change to ionic coordinates.

If you were expecting something like a Jahn-Teller distortion caused by crystal-field splitting, you will need to start with a slightly symmetry broken configuration: the code cannot break symmetry spontaneously.

Best,
Shankar
