### ISSUE TITLE
JDFTx crash in DOS calculations with SOC

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#174]
JDFTx crashes when requested to calculate DOS of the s-character (e.g. 'OrthoOrbital C 1 s' option in the 'density-of-states' command) for any element in calculations with SOC, requested by the 'spintype spin-orbit' command. I am using the full-relativistic SG15 pseudos.

**Comment by shankar1729** [comment]
Thanks for catching this bug: fixed in [latest commit](https://github.com/shankar1729/jdftx/commit/20f1b6).

**Comment by sergbuto** [comment]
JDFTx also crashes when asked to calculate partial DOS for initially empty valence orbitals which are not included to the ONCV pseudopotential configuration due to zero population. For example, 6d states for Pu. In this case, the 'OrthoOrbital Pu 1 d' option causes a crash.

**Comment by shankar1729** [comment]
Thanks for catching that! I had a n, l range check for Orbital, but had forgotten to include OrthoOrbital in that check when I added that feature. 

Fixed in [latest commit](https://github.com/shankar1729/jdftx/commit/cb8b3280); JDFTx will now exit at initialization with a helpful error message for unavailable orbitals.

Best,
Shankar
