### ISSUE TITLE
Parallelization with hybrid functionals

### ISSUE THREAD

**Issue by taylor-aubry** [shankar1729/jdftx#186]
Hello Shankar + JDFTx community,

I am trying to run the primitive cell of the 2D material VS2 using a hybrid functional and as others have noted it is taking a long time. I just want to check if there is anything else I can do to speed up the calculation.

I have ~1 nm of vacuum and am using Coulomb truncation in the z-direction. I am running a 12 x 12 x 1 k-point mesh which reduces to 19 k-points under symmetry. I did a quick benchmark of 1 electronic minimize step for 2/4/5/19 nodes which took 8/4.5/3.5/1.25 hours and 48/53/52/71 AUs, respectively. Based on this, I think 5 nodes is optimal.

I am now running on SLURM with, e.g.:
#SBATCH --cpus-per-task=1
#SBATCH --nodes=5
where each of our nodes has 36 cores. 

I have updated JDFTx within the last few months so I think this should be implementing the ACE acceleration technique but I am not sure. I have attached all relevant I/O files as .txts.

Thank you for any advice,
Taylor

[totalE.in.txt](https://github.com/shankar1729/jdftx/files/7367733/totalE.in.txt)
[totalE.out.txt](https://github.com/shankar1729/jdftx/files/7367734/totalE.out.txt)
[VS2.ionpos.txt](https://github.com/shankar1729/jdftx/files/7367735/VS2.ionpos.txt)
[VS2.lattice.txt](https://github.com/shankar1729/jdftx/files/7367736/VS2.lattice.txt)
[VS2.sbatch.txt](https://github.com/shankar1729/jdftx/files/7367737/VS2.sbatch.txt)

**Comment by shankar1729** [comment]
Hi Taylor,

It appears that you are only using MPI parallelization and not threads, which is much more efficient when practical. For your five node case, please try running with -N 5 -n 10 -c 18 (5 nodes, 10 processes, 18 cores/process) and similar combinations. I suspect you will get much better throughput in those cases than your pure-MPI runs.

Best,
Shankar

**Comment by taylor-aubry** [comment]
Hi Shankar,

Thanks for this, I will try it out right away and update. 

I had initially run with just -N 19 (which automatically uses all 36 cores/process) and this took ~16 hours to run 1 electronic minimize step. Setting -N 19 with -c 1 vastly improved this to 1.25 hours per step, but I think I can see how using 5 nodes with more processes and fewer cores per process could lead a more optimal parallelization. Thanks, I am still trying to wrap my head the basics!

Taylor
[VS2.out.txt](https://github.com/shankar1729/jdftx/files/7368648/VS2.out.txt)

**Comment by shankar1729** [comment]
Hi Taylor,

Looking at your log files, maybe another thing to try is to use SCF instead of minimize. The idea of ACE really only applies in the SCF context: create a compressed representation of exchange at current hamiltonian, optimize within that subspace and then iterate.

In doing this, the cost of each exchange operator construction will not change (about 1 hour in your best case above), but the number of times it needs to be computed could be reduced within SCF. So you may be able to get ~ 4-5 SCF cycles in the same time. Please try that (with your optimal parallelization setup above) and let me know if it helps.

Best,
Shankar
