### ISSUE TITLE
energyDispersion_Interband：Doubts about the normalization method

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#190]
Dear Dr Shankar,
I tried to use the energy distribution code. But I have some doubts about the normalization part. I would like to know why "omegamMid" is used in normalization as shown in the figure. 
I tried different calculations, with “omegaMid” or without “omgeaMid” to the normalization(as shown in the comment line in the figure), and the final results did not make a big difference. The result is attached at the end. So can I remove the “omegaMid” item in the calculation? 

![1636945676(1)](https://user-images.githubusercontent.com/92436849/141716078-e1492c5d-c2a1-4bf3-b5ef-c9f9827c37da.png)
![image](https://user-images.githubusercontent.com/92436849/141716133-56919167-bdf1-4aff-a807-5bcf3fb6c9a6.png)
![image](https://user-images.githubusercontent.com/92436849/141716166-d25f5945-f380-4621-bf6a-57021be28059.png)

**Comment by shankar1729** [comment]
Indeed, that term is completely optional.

In ACS Nano 10, 957 (2016), we introduced that factor in the plot of P(omega, epsilon) so that the intraband transitions show up as a flat plateau. So this choice of normalization (adding the omega factor) makes it such that a uniform probability of electrons and holes up to the photon frequency has a probability of 1.

Also this makes P dimensionless for easier plotting. Without this factor, P has units of 1/energy because it is a probability density with respect to carriers. 

Best,
Shankar
