### ISSUE TITLE
energyDispersion_Interband：still have doubts about the normalization method

### ISSUE THREAD

**Issue by hwmmm1** [shankar1729/jdftx#191]
Dear Dr. Shankar,
   Sorry to be a bother.  I read your paper titled  "Nonradiative Plasmon Decay and Hot Carrier Dynamics: Effects of Phonons, Surfaces, and Geometry" and met a problem.
As you said in Figure 4，page 5, “For each frequency, P(ω,ε) is normalized such that it equals 1 for a flat distribution”. How should we understand the **falt distribution**?  Does the **flat distribution** have a certain physical meaning here?

Looking forward to your reply.

**Comment by shankar1729** [comment]
Flat distribution = uniform distribution of electron and hole energies in the allowed range i.e. zero to the photon energy (by energy conservation). Essentially, this means that P(omega, epsilon) does not depend on epsilon. So let's say P(omega, epsilon) = f(omega).

If we go with conventional normalization of the probablity distribution at each photon energy, we would have integral over epsilon ranging from epsilon = 0 to omega (max allowed for each photon energy) of P(omega, epsilon) = 1. This yields integral_(epsilon=0)^omega f(omega) = 1 i.e. f(omega) = 1/omega. Therefore, for a flat / uniform distribution of electrons and holes that is typical for intraband transitions, we end up with P(omega, epsilon) = Theta(omega - abs(epsilon)) / omega, where Theta is the unit step function.

This is perfectly valid, but makes the plots really hard to read because you will get a spike approaching omega = 0. Consequently to see the features better, we use the normalization integral_epsilon P(omega, epsilon) = omega i.e. multiply the above by omega. With this normalization, a flat distribution would be P(omega, epsilon) = Theta(omega - abs(epsilon)), which is the flat plateau of height 1 that you see in the intraband regions. This also allows you to more clearly see how the interband transitions localize the carriers in energy (in the blue hills at higher energy).

Best,
Shankar
