### ISSUE TITLE
v 1.7.0: memory corruption (Intel compiler)

### ISSUE THREAD

**Issue by sbecuwe** [shankar1729/jdftx#208]
Hello

I'm trying to install JDFTX 1.7.0. Compilation goes fine, but "make test" fails.
I'm using MKL 2020.04, icc 19.1, FFTW 3.8, GSL 2.5

I have tried 
```
-DEnableMKL=yes -DEnableMPI=yes -DForceFFTW=yes -DMKL_PATH=$MKLROOT \
-DThreadedBlas=yes -DFFTW3_PATH=$EBROOTFFTW -DGSL_PATH=$EBROOTGSL \
-DEnableCUDA=yes 
```
but also switching off MPI, FFTW or ThreadedBlas doesn't change anything.
Part of the output:
```
$ make test
Running tests...
[...]/ctest --force-new-ctest-process
Test project [...]
      Start  1: openShell
*** Error in `[...]/jdftx': realloc(): invalid pointer: 0x0000000001b1cc10 ***
      Start  3: moleculeSolvation
*** Error in `[...]/jdftx': malloc(): memory corruption (fast): 0x0000000002187560 ***
      Start  4: ionSolvation
*** Error in `[...]/jdftx': corrupted size vs. prev_size: 0x 
      Start  5: latticeOpt
*** Error in `[...]/jdftx': malloc(): memory corruption (fast): 0x00000000026d6360 ***
```

Do you have a working setup for Intel? If so, is it possible to share compile instructions and version numbers of libraries used?
Many thanks.

Stefan

**Comment by shankar1729** [comment]
Hi Stefan,

Please see this recent issue: https://github.com/shankar1729/jdftx/issues/206

It appears that newer Intel compilers are creating an unknown issue, perhaps related to threading. I'd strongly recommend switching to the GNU compiler, still linking to MKL. You should not see any performance difference due to the compiler because most of the time is spent within BLAS and FFT calls anyway (which will be the same if you link to MKL).

Best,
Shankar
