### ISSUE TITLE
Slow performance in DOS calculation at fixed potential

### ISSUE THREAD

**Issue by J-Plankton** [shankar1729/jdftx#216]
Dear Shankar,
I tried to calculate the DOS of a system in the vacuum which only cost four hours. Then I  calculated the same system at a fixed potential, however, more than 48 hours to get the result. Could you give me any advice on this situation? I have attached the output file below. After that, I attempted to reduce the convergence threshold of energy difference in the command of electronic-minimize, whereas the calculation seemed to be stuck at "Initial electronic minimization" for two hours. Could you give me any advice on these situations? I have done the fixed-potential calculation before, can I start to calculate DOS  at the final state of the previous one?
THANKS，
Lois
[dos-at-fix-potential.output.txt](https://github.com/shankar1729/jdftx/files/8223948/dos-at-fix-potential.output.txt)

**Comment by J-Plankton** [comment]
Dear Shankar,
I have attached output files of the vacuum DOS calculation and the fixed-potential calculation without DOS below,respectively.
THANKS again,
Lois
[dos-vacuum.output.txt](https://github.com/shankar1729/jdftx/files/8224409/dos-vacuum.output.txt)
[fixed-potential-cal-without-DOS.output.txt](https://github.com/shankar1729/jdftx/files/8224410/fixed-potential-cal-without-DOS.output.txt)

**Comment by shankar1729** [comment]
Hi Lois,

I see: you are changing the k-point sampling and number of bands between the DOS calculations and the ones without. Minor comment there: your fixed potential calculation is using 28 MPI processes on 5 states, so that is very inefficient. Please see the docs and previous threads here on using hybrid  MPI and threads effectively.

So, for the DOS at fixed potential, I would recommend "dump End Vscloc" from the fixed potential calculation run with the smaller k-mesh etc. (Based on your filenames, this would create sol.Vscloc) Follow that up with a non-self-consistent calculation that uses "fix-electron-potential sol.$VAR", whatever high k-mesh you need and the density-of-states command. This will be *much* faster. You can use this to accelerate DOS whenever running self-consistent calculations is too expensive with high k sampling.

Best,
Shankar

**Comment by J-Plankton** [comment]
Dear Shankar,
Sorry to bother you again. 
I follow your suggestions above to calculate the DOS at a fixed potential. It's very fast. I checked the final output file of the DOS calculated with the command of "fix-electron-potential sol.$VAR", which was obtained from the fixed potential calculation (mu = -0.163167) before, that the mu is  -0.157567410. The output code is 
'Setting wave functions to eigenvectors of Hamiltonian
        FillingsUpdate:  mu: -0.157567410  nElectrons: 316.000000'.  
Did not the DOS calculate at a supposed potential  (mu = -0.163167)? I have attached the output files of the fixed-potential calculation and the DOS calculation. 
Thank you so much,
Lois  
[dos-pdos-test1.out.txt](https://github.com/shankar1729/jdftx/files/8239959/dos-pdos-test1.out.txt)
[fix-potential-test1.out.txt](https://github.com/shankar1729/jdftx/files/8239960/fix-potential-test1.out.txt)

**Comment by shankar1729** [comment]
Hi Lois,

The fillings calculated in the non-self-consistent calculation have no impact on the electronic eigenvalues, and hence on the DOS (since the Kohn-Sham potential has been read in from the fixed-mu calculation). So you can just ignore that line of the output in the log file.

Best,
Shankar
