### ISSUE TITLE
Structure optimization under constant potential

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#227]
Hi Shankar,

Recently, I did some calculations about structure optimization of  water molecule adsorbed on metal surface, and I found  some strange results when I use different values of "target-mu",.

for example, if I use "target-mu -0.1713" ( 0V vs. SHE ), the final structure will be reasonable(fig.1), however, if I use "target-mu -0.0978"( -2V vs. SHE ), the final molecule structure will be scattered, the H atom in original H2O molecule will be pushed away and the O-H bond is broken(fig.2). I think it is unreasonble to break the O-H bond only under -2V vs. SHE, I wonder whether there are some inappropriate parameters in my input file, could you give me some suggestions? 

fig1
![fig1](https://user-images.githubusercontent.com/54838707/170818035-12dc95c4-89f4-4525-90e3-de9d6e60469c.png)

fig2
![fig2](https://user-images.githubusercontent.com/54838707/170818048-9655aec4-d7c4-4828-8d25-67a96ff0815c.png)

input file:
[Charged.in.txt](https://github.com/shankar1729/jdftx/files/8790789/Charged.in.txt)
[contcar.ionpos.txt](https://github.com/shankar1729/jdftx/files/8790790/contcar.ionpos.txt)
[contcar.lattice.txt](https://github.com/shankar1729/jdftx/files/8790792/contcar.lattice.txt)

**Comment by shankar1729** [comment]
This could be because a bare proton is over-solvated by the solvation model. It would be useful to examine the bound charge in the solvent or the solvation cavity (by respectively including BoundCharge or FluidDensity in the dump command) to confirm this.

If that's the issue, then it would require an explicit second water to physically capture the proton, and ensure that the O-H bond breaking happens at an appropriate potential.

Best,
Shankar
