### ISSUE TITLE
Very very slow when running simple optimization for a metal-slab

### ISSUE THREAD

**Issue by KevinLiu7** [shankar1729/jdftx#228]
Hi,

This is my first time to use JDFTx and I want to calculate the adsorption energy of an oxygen atom on a Cu 111 slab surface. The code is attached for the Cu-O adsorption strucure and the model includes 3x3x4 (36) Cu atoms and an O atom on the fcc position at the top.

The problem I met is that running these codes is really really slow, firstly stuck at LCAOMinimize part. It takes me around 1 hour to run 30 iterations of LCAOMinimize. JDFTx told me "None of the convergence criteria satisfied after 30 iterations" and then move to the geometry optimization. The geo optimization is also very slow that the first ionic step costs around 90 minutes to finish. 

I use 24 cores to do the optimization on our university's supercomputer. When I use VASP to do the optimization using 24 cores (the same initial structure), the job finishes in around 5 minutes.  I think there must be something wrong in my codes leading to such a slow running. Can anyone help me check the codes? 

Thank you!

[Cu_O_fcc.zip](https://github.com/shankar1729/jdftx/files/8828092/Cu_O_fcc.zip)

**Comment by shankar1729** [comment]
Please also post the job file and log file so that we can see the process and thread configuration used.

**Comment by KevinLiu7** [comment]
Hi Shankar,

Thanks for the reply. All files in the running folder are attached. This is only the Cu slab (36 Cu atoms, no O atom).

Best
[Cu_surface.zip](https://github.com/shankar1729/jdftx/files/8828326/Cu_surface.zip)

**Comment by shankar1729** [comment]
Hi Kevin,

Please read the Getting Started page on running hybrid MPI - threads code with the appropriate number of processes for JDFTx runs. You have nStates = 5 in this run, for which 5 processes are the maximum that will be used. You can use more cores using threads for each process.

For your 24-core run, you may want to try one of the following modes of running:

     #SBATCH -n 5 -c 4   # i.e. run 5 processes with 4 cores/process

     #SBATCH -n 2 -c 12   # i.e. run 2 processes with 12 cores/process, i.e. 1 socket/process

You may also need to specify something like "--bind-to none" in the mpirun command, depending on your MPI version.

Also, I notice in that your output file that JDFTx detected 128 cores on your system. You should probably also check how many cores are actually on the machine. You can post the output of "lscpu" run on the compute node to help identify your node configuration in more detail.

Best,
Shankar

**Comment by shankar1729** [comment]
Yes, that's right.

**Comment by KevinLiu7** [comment]
Thanks again! I will close this issue.

**Comment by KevinLiu7** [comment]
Hi Shankar,

Sorry to bother you again. I tried what you said and changed the command in the submission .sh file. For the example in this article (https://www.sciencedirect.com/science/article/pii/S2352711017300559), I used the same command as you (4 processes and 8 threads each), costing me around 2h. I think that's OK. But for the Cu system, it still cost me over 8 hours (I set 8 hours for the job running time and it is not finished). Could you do me a favor to check if there is any problem? I used 4 processes and 24 threads each for the Cu system.

Thank you very much!

Best,

Kaida

[Cu_surface.zip](https://github.com/shankar1729/jdftx/files/8856432/Cu_surface.zip)
[SoftwareX_test.zip](https://github.com/shankar1729/jdftx/files/8856452/SoftwareX_test.zip)

**Comment by shankar1729** [comment]
Please post output of "lscpu" run on one of the compute nodes. You seem to be oversubscribing the nodes and it is unclear to me how your compute nodes are actually configured (number of sockets, physical cores/socket, threads/core etc.).

If it took 2 hours today to run the example that took me ~ 15 minutes more than five years ago, then there is something certainly sub-optimal about the build or run configuration. Please also post the CMakeCache.txt from your build directory so that we can understand the library versions being used.

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar, 

Thank you for the reply. Here are the results of lscpu:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
**Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             2**
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
**Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz**
Stepping:              2
CPU MHz:               1252.000
CPU max MHz:           2500.0000
CPU min MHz:           1200.0000
BogoMIPS:              4994.46
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm arat pln pts md_clear spec_ctrl intel_stibp flush_l1d

And the CMakeCache.txt is also attached. I guess there might be something wrong with my fftw package. After the installation of JDFTX, every time I have to manually module load the fftw.
[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/8856791/CMakeCache.txt)

Really appreciate!

Best,

Kaida/Kevin

**Comment by shankar1729** [comment]
Actually the FFTW library will be fine: you should be loading modules for libraries used in your run; that is the expected behavior in most clusters. (This may be different for statically linked programs, which maybe VASP does. JDFTx is linked dynamically by default.)

I think your main performance issue is coming from the BLAS Library. From your CMakeCache.txt, you are linked to the default BLAS at /usr/lib/libblas.so, which is typically going to be terrible! (These are typically reference implementations with almost no optimization such as use of vector instructions.) Since you have Intel CPUs, you should load the MKL module and link to MKL by setting EnableMKL=yes and specifying MKL_PATH if needed: see the instructions at http://jdftx.org/Customization.html

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar,

Thank you for the reply. I met some problems during the re-compiling to add "EnableMKL=yes". The MKL path cannot be found. I have already asked for help from our University's IT helpdesk. Will let you know the results ASAP.

Really appreciate,

Kaida

**Comment by KevinLiu7** [comment]
Hi Shankar,

Finally I re-complie the JDFTX with the tag -D EnableMKL=yes and also EnableFFTW=yes. Also for people who may also encouter this problem in the future: when you install JDFTX on a linux system (especially a supercomputer), the MKL path may look like this in the $LIBRARY_PATH: 

/panfs/roc/intel/x86_64/2018/parallel_studio_xe_msi/compilers_and_libraries_2018.0.128/linux/mkl/**lib/intel64**

If we type this path, JDFTX cannot indentify it. We have to type like this:

/panfs/roc/intel/x86_64/2018/parallel_studio_xe_msi/compilers_and_libraries_2018.0.128/linux/mkl/

However, after the re-isntallation, the time spent on the calculation is still around 2 hours. Could you please have a check on the CMakeCache file again? Thank you very much!
[CMakeCache.txt](https://github.com/shankar1729/jdftx/files/8880513/CMakeCache.txt)

Best,

Kaida

**Comment by shankar1729** [comment]
Thanks for the update! Can you please post the output file and submission job file with the updated version?

**Comment by shankar1729** [comment]
Also, please rerun after compiling with EnableProfiling=yes, and set the ionic minimize steps to 0 so that the job actually finishes and provides the  profiling output. (That is, don't set up a long job and interrupt it midway.) This will allow us to isolate which operations are being unreasonably slow, if any.

**Comment by KevinLiu7** [comment]
Hi Shankar,

Thanks for the reply! I didn't run the test job to the end. I found out the time between each step is basically the same as the former version (each LACO step takes ~10s and each electron step takes ~17s). I may recompile with EnableProfiling=yes after you check the submission and output files.

Best,

Kaida

[test_with_MKL.zip](https://github.com/shankar1729/jdftx/files/8880673/test_with_MKL.zip)

**Comment by shankar1729** [comment]
This job is oversubscribed: you have asked for 24 threads each for 4 processes, leading to 96 threads to be launched. In contrast, all processes are running on the same node because you did not tell slurm that each process needs 24 cores.

So basically, move the "-c 24" from the jdftx argument list into the SBATCH line. (JDFTx will automaticlaly pick up -c from slurm, so you don't need to repeat it. But it won't work the other way: slurm doesn't look at the arguments passed to jdftx.)

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar,

One good news: Not changing the submission file, the running speed for the Cu36 system (each LCAO step ~15s, each electron step ~45s) becomes much faster compared to the former version (each LCAO step ~30s, each electron step ~120s). I think MKL is working and doing a good job.

One bad news: Changing the submission command still does not improve the performance on the test example or the Cu36 system. I am still trying to figure out what happens. I use these commands. Did I understand your words in a wrong way?

#SBATCH --time=8:00:00
#SBATCH --ntasks=96
#SBATCH --mem=60g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=liu01485@umn.edu
#SBATCH -n 4 -c 24
module load intel
module load ompi/intel
module load fftw/3.3.10-double-ompi-4.1.1-gnu-9.2.0

ulimit -s unlimited

mpirun -n 4 jdftx -i Cu_surface.in -o Cu_surface.out

**Comment by shankar1729** [comment]
Please post the output files for the times you are quoting so that we can see the actual process and thread configuration picked up by JDFTx.

Also, note that the suggestion of -n 4 -c 24 nodes was based on your previous example of some Pt surface that had nStates = 20. (The 20 reduced k-points split well and evenly over 4 processes.) If I remember correctly, your Cu system ends up with nStates = 5 which is not well divided into 4 processes. You may want to do -n 5 -c 24 for this one. So after this iteration, please go back to the discussion on the Getting Started page and make sure you follow the recommendations of selecting process counts.

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar,

Thanks for the advice. I changed the number of n and it does improve the performance. Let's just focus on the test (example in the SoftwareX article) job. I use n=20 and 128 threads (shown in the output file) and it costs me around 1h, saving me 50% time compared to using n=4. However, I guess that's still very slow based on your experience. I will compile with the Enableprofile flag and upload the results on Monday. 

Thanks,

Kaida
[test_20 process.zip](https://github.com/shankar1729/jdftx/files/8887379/test_20.process.zip)

**Comment by KevinLiu7** [comment]
Also, I have tried the sbatch -n 4 -c 24 command and I don't think that works. Each node of our supercomputer has 128 cores and each core has 1 thread. So I just use 1 node.

**Comment by shankar1729** [comment]
Your lscpu output above indicated 24 cores: maybe you ran that on the log in node and not on the compute node via sbatch? Please provide the cpu details of your compute node to get a more realistic picture of the expected performance.

Glad to hear the performance improved: indeed it seems a bit slow for 128 cores. Your run took about 7 minutes for the vacuum part (see the time on the last ElecMinimize line just before "Vacuum energy after initial minimize") and 9 minutes more from that point to where the first ionic step at fixed mu completes. These are the times to compare with the SoftwareX paper, not the entire IonicMinimize (the figure caption notes that it is for the initial geometry). So you can turn of IonicMinimize in th einitial performance benchmarks.

Your times are about 2x slower than the 3 minutes and  5 minute times observed in the SoftwareX paper for 10 processes x 8 cores/process = 80 cores. However, note that those 80 cores involved 10 sockets on 5 compute nodes with 16 cores each. Just raw core numbers are not enough, your 128 core single node may have lower total memory bandwidth and cache size than those 5 nodes combined. So these times may be okay, but we need detailed lspcu output of your compute node to confirm this.

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar,

Thank you for the detailed information about the running time. The job I submit will run on the agsmall node (https://www.msi.umn.edu/partitions) and the website says it has 128 cores per node. I guess the lscpu information I provide before is just for running jobs interactively but not the node the task works on. The output with enableprofile was attached. I would appreciate it if you could have a look.

Also, I guess the problem I met is that I can run 20 processes but each process only uses 1 core. In the .out file, it shows
"Running on hosts (process indices):  acn229 (0-19)", acn229 is the agsmall node the job is working on.. It has 128 cores (0-127) and I think 0-19 means it only uses 20 cores. I have asked our IT helpdesk to figure out how to use multiple cores for each process and how to use more memory. Let me wait for their reply.

Thank you very much!

Best,

Kaida
[test_20 process_enable_profile.zip](https://github.com/shankar1729/jdftx/files/8893945/test_20.process_enable_profile.zip)

**Comment by shankar1729** [comment]
Just launch a job requesting a single node and process with the only command within the job file being "lscpu". That should get you the CPU details needed. If you are not able to get this, at least find out the exact CPU model and number of such CPUs per node from your campus supercomputer's website or equivalent source.

The output acn229(0-19) means process indices 0 - 19 are running on node named acn229. So that looks fine.

For the profiling output, please run a version with "ionic-minimize nIterations 0" so that I can compare directly with the profiling output from the JDFTx paper runs. This will also be a quicker run that can be used to more rapidly check for performance issues at your end.

Best,
Shankar

**Comment by KevinLiu7** [comment]
Hi Shankar,

The two files, lscpu output, and no Ionic step job output, were attached. Thanks!

Best,

Kaida

[cpu.txt](https://github.com/shankar1729/jdftx/files/8894481/cpu.txt)
[test_no_Ionic_step.zip](https://github.com/shankar1729/jdftx/files/8894482/test_no_Ionic_step.zip)

**Comment by shankar1729** [comment]
Note that third-party BLAS libraries like OpenBLAS may also be a fine option, if you already have modules for those.

**Comment by KevinLiu7** [comment]
Hi Shankar,

I think you are correct. I submit the job with the same sbatch file to an intel node (Xeon E5-2680 v3) and it saves 20% time. However, our university does not have a lot of intel cores, so I need to spend more time in the queue to wait for the intel cores. Thank you very much for the detailed reply and helping me figure out how to improve the performance. I learn a lot from this process. I guess the time spent on each job, although not as fast as VASP, is acceptable now, showing a tremendous drop compared to the initial case. 

I will close this issue. Again, I really appreiciate your help!

Best,

Kaida

**Comment by moyulyy** [comment]
Hello, Shankar,

When I ran jdftx on only one computer for zpe calculation, I used all its 40 cores and ran the script as
#PBS -q batch 
#PBS -o /tmp 
#PBS -e /tmp 
#PBS -N ZPE-OH
#PBS -M 1944327947@qq.com 
#PBS -m e 
#PBS -l nodes=1:ppn=40 
#PBS -l walltime=36:00:00  
export INTEL_HOME=/opt/intel 
source ${INTEL_HOME}/bin/compilervars.sh intel64 
source ${INTEL_HOME}/mkl/bin/mklvars.sh intel64 
source ${INTEL_HOME}/impi/5.0.2.044/bin64/mpivars.sh intel64 
NP=`cat ${PBS_NODEFILE} | wc -l` 
cd $PBS_O_WORKDIR 
mpirun -hostfile $PBS_NODEFILE -np $NP /opt/build/jdftx -i ZPE.in > ZPE.out   2>&1

And the output file shows the Run totals: 40 processes, 40 threads, 0 GPUs, and nStates=8
Unfortunately, after about 4 hours of running, the following information shows that the memory (32GB) is insufficient.

------ Vibrations::calculate() -------
WARNING: Vibrations module is experimental. Please report bugs!
Compare results with and without symmetries and report discrepancies.
Degrees of freedom: 6 total, 6 symmetry-independent.
-------- Electronic minimization -----------
APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)

However, I ran many similar computations on another computer cluster with two nodes, each with 36 cores，
The entire calculation takes only about two or three hours, and the output file shows the Run totals: 2 processes, 72 threads, 0 GPUs, and nStates=8

Therefore, I believe there are issues that need to be addressed in running or configuring jdftx on this 40-core device to maximize its computing performance and shorten computing time.

Attached is the device information of the computer device and would like your suggestions or any insights on solving the problem.

【】$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    1
Core(s) per socket:    20
Socket(s)：            2
NUMA node(s)：         2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:：          Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
Stepping:              7
CPU MHz：              2900.061
CPU max MHz:           4000.0000
CPU min MHz:           800.0000
BogoMIPS：             4200.00
NUMA node0 CPU：       0-19
NUMA node1 CPU：       20-39
【】$ free -h
              total        used        free      shared  buff/cache   available
Mem:            30G         21G        9.2G         22M        416M        9.1G
Swap:           15G        284M         15G
Also, noting that nStates=8, does this mean that you have the best parallel computing performance when using 8 nodes?
When using 8 nodes, is there a requirement for the number of cores per node? Is more auditing better?

Thank you again for your generous contribution to my issue.

**Comment by shankar1729** [comment]
You don't need 8 nodes because nStates = 8, but you must not exceed nProcesses = 8.

On your 40-core node, try running with 8 processes and 5 threads; that would be `-n 8 -c 5` in SLURM, but I'm less familiar with PBS to mention its analogous details. Also, try `-n 2 -c 20` to use one process per physical socket (and all cores of each socket as threads).

If these runs with more threads/process seem to be running very slowly still, you may have a CPU thread binding issue, where all threads launched by a process get pinned to a single core. You can address this in OpenMPI, for example, by adding `--bind-to none` in the mpirun command line.

Best,
Shankar
