### ISSUE TITLE
BLAS CBLAS library

### ISSUE THREAD

**Issue by Jinzz98** [shankar1729/jdftx#243]
Hi,

I compiled jDFTx with Intel oneMKL and openBLAS. When I checked CMakeCache file, I noticed there are several blas library PATHs including blas_mkl and GSL_BLAS_LIBRARY.

1. Since we use intel MKL, why need GSL BLAS library?

2. At first, error occurred,  saying Could not find CBLAS shared library. So I installed openBLAS and compiled jDFTx by adding -D CBLAS_LIBRARY=libopenblas.so to the command line.  Is it OK? Would this degard jDFTx‘s performance？

**Comment by shankar1729** [comment]
First, use either MKL or openBLAS, but not both. You may end up with a weird situation if you link both because they each have BLAS and LAPACK implementations that may conflict.

CMake's find scripts (not written by us) create a bunch of variables about all the versions of libraries they find, so you may have several BLAS libraries found, but only one should be used. Additionally, linking to GSL requires linking to a BLAS library, and one of these variables might be referring to the library used to satisfy GSL's BLAS requirement.

If that was not confusing enough, the CBLAS library is yet another independent requirement which provides a thin layer to C/C++ applications for more sensibly calling the underlying Fortran BLAS libraries. You can use any implementation of the CBLAS layer, as they just forward to whatever BLAS you have linked to. If you are using MKL or openBLAS, each of them have CBLAS built in. You can also use the cblas layer provided by GSL, and it should not make a performance difference. Just don't mix two full BLAS libraries like MKL and openBLAS though!

Best,
Shankar

**Comment by Jinzz98** [comment]
It seems that I‘d batter recompile jDFTx .
