### ISSUE TITLE
Calculation results do not match Materials Studio

### ISSUE THREAD

**Issue by Severus0723** [shankar1729/jdftx#250]
Dear Shankar,
       Recently, I tried to use JDFTX to study the deposition of lithium dendrites, but when I used JDFTX to calculate the optimal configuration of a lithium atom to deposit on the crystal, I found that the results calculated using JDFTX  are not the same as the "Materials Studio" results.
Specifically, the calculation results of materials studio show that the most favorable site for the deposition of lithium atoms should be the bottom site (see appendix). The JDFTx calculation results show that the most favorable site for the deposition of a lithium atom on the surface seems to be the top site (with the lowest energy. See attachment). So I am wondering, is it because the added solvation model is not suitable for this system? Because when I remove the solvent, the calculation results are consistent with Materials Studio. Or am I using some parameters that are not quite right? Or is this calculation correct?
[Li.zip](https://github.com/shankar1729/jdftx/files/9623493/Li.zip)
best,
jay

**Comment by shankar1729** [comment]
Hi Jay,

The materials studio calculations are in vacuum, and the vacuum calculations agree with each other, but your solvated result changes the preferred adsorption site, right?

Also looking at your adsorption energies, it appears that the solvated version brings all the energies much closer to each other compared to the vacuum. This is quite reasonable because in vacuum, undercoordinated atoms at the surface have a higher energy but also likely have a larger partial charge; this larger partial charge leads to the more unstable surface terminations getting solvated more.

So, all in all, sounds physical to me. Note that the whole point of using a solvation model is to capture effects beyond the vacuum calculations. Of course make sure everything converged correctly, but remember that comparing against vacuum DFT calculations is not a benchmark for correctness.

Finally, I noted in your output files that your parallelization is still far from optimal. For example, you used 64 processes on a calculation with nStates = 6. If you launched this with 6 processes and appropriate number of threads (eg. srun -n 6 -c 20 for the same 128 cores), you could get an almost 10x speedup. Please see the Getting Started page and numerous discussions here on how to use hybrid MPI/Threads correctly.

Best,
Shankar
