### ISSUE TITLE
Does GCP JDFT account for changes in Fermi level?

### ISSUE THREAD

**Issue by krl52** [shankar1729/jdftx#254]
I am trying to solve a particular problem with CO* adsorption energies becoming unexpectedly positive when the room-temperature entropy correction is added. In the JDFTx output file, I see that the electronic entropy ("TS") is a component of the total DFT energy. In the electronic entropy contribution, does JDFTx account for the additional change/uncertainty of the Fermi level when an applied potential is added (grand canonical DFT)?

**Comment by shankar1729** [comment]
The electronic entropy term is calculated from the occupation factors corresponding to the selected smearing method. That is, it is based on f log f + (1-f) log(1-f) for Fermi smearing and involves error functions and gaussians instead for the remaining smearing methods.

The grand-canonical case does not change this, and only adds an overall -mu N term.

Independently from this, you could be correcting the entropy from the high smearing calculation to the room-temperature value (this should match the smearing scheme that you are using). There is no different consideration here due to GC-DFT.

I'm not sure if that's what you were asking though, so please clarify further if that did not address your question.

Best,
Shankar

**Comment by krl52** [comment]
My understanding is that the electronic entropy is calculated from the Fermi-Dirac distribution function, as you described above, which depends on the chemical potential (Fermi level). When you fix the electron chemical potential using target-mu, is the fixed value used to determine f in your equation above?

**Comment by shankar1729** [comment]
Yes, the fixed mu determines the occupation factors in GC-DFT, and the spin entropy is computed from those occupation factors in exactly the same way.

Best,
Shankar

**Comment by krl52** [comment]
I see, that makes sense. I’m wondering, then, if you might have any insight into this particular problem I’m having with determining CO* binding energies. The DFT energies alone are on the order of -0.1 eV with a full monolayer of co-adsorbed hydrogen. When corrected for the rotational/translational entropy at room temperature, the binding energy becomes significantly more positive (~0.5 eV). This is inconsistent with our experimental observations (we expect CO* binding to be favorable, even with coadsorbed hydrogen). Here is what I have tried so far:
1. I used the RPBE functional to subvert some of the issues with the “CO adsorption puzzle”.
2. The RPBE functional is designed to improve the energetics of CO adsorption, so the gas phase correction for CO (typically used to correct O2 energy) is small.
3. van der Waals interactions - based on this paper (https://doi.org/10.1021/acs.jpcc.7b00365), including van der Waals interactions with the RPBE functional results in poorer agreement with the experimental binding energy.
4. ZPE and vibrational energies are included but don't significantly affect the result. 
5. Configurational entropy and heat capacity contributions are expected to be small  
6. Spin polarization does not seem to have an effect
7. Including an explicit water molecule to account for effects of hydrogen bonding stabilizes CO* by ~0.1 eV, but the CO* binding energy is still too positive.

**Comment by shankar1729** [comment]
I don't have much specific experience with this system or the RPBE functional, so don't have much to add.

One clarification on your original question: when you say the room temperature entropy correction, you are referring to the gas-phase entropy of CO, right? And not electronic entropy? Because if electronic entropy made a big difference, you may need to converge smearing schemes and widths very carefully.

Best,
Shankar

**Comment by krl52** [comment]
Yes, I'm referring to the gas phase entropy of CO. For the smearing, I tried two different smearing widths (0.01 Ha and 0.001 Ha) with the Fermi scheme. The respective entropic energy contributions are 0.03044709148 Ha (adsorbate on slab) - 0.03035580975 Ha (clean slab) = 0.0025 eV (difference) and 0.0006712548512 - 0.0001364824317 = 0.0146 eV. Does that seem like a notable difference to you?

**Comment by shankar1729** [comment]
Right, those electronic entropy contributions seem reasonable and negligible on the scale of energies you discuss above, so that's not the issue. It must be a binding energy error, perhaps of the DFT functional.

One final consideration, how did you determine that the hydrogen co-adsorption is a full layer? Could it be that that your too-positive energies are coming from adsorbate repulsions, and that in reality, you have more room around the adsorbed CO?

Best,
Shankar

**Comment by krl52** [comment]
Okay, that's what I thought, thank you! I think there should be 1 ML co-adsorbed hydrogen because we observe hydrogen evolution experimentally under these conditions. Only top-adsorbed hydrogen is active for hydrogen evolution, but hydrogen adsorption is more favorable in hollow sites, so hydrogen must fill all the hollow sites before it can fill the top sites. It might be possible that the *CO coverage is lower, so I'm working on testing that.
