### ISSUE TITLE
Slab optimization error

### ISSUE THREAD

**Issue by zzhjglz** [shankar1729/jdftx#258]
Hi Shankar,

I constructed a slab structural model Ti3C2O2, and I used JDFTx to optimize. 
I'm a freshman and maybe there is something wrong in my lattice.
The calculation crashed with the following error:

Lattice direction 001 is not perpendicular to the other two basis vectors.

The lattice and ion position information are:
lattice 
         3.2208699883  -1.6107074306  -0.0020896515
         0.0003130007  2.7892009477   -0.0048507795
         0.0003060007  0.0004619992   21.9999993660
latt-scale 1.88973 1.88973 1.88973  #Convert lattice vectors from Angstroms to bohrs

ion Ti  0.314082472         0.714067424         0.167229453 1
ion Ti  0.647608358         0.380718285         0.422880435 1
ion Ti  0.980865830         0.047428539         0.295039415 1
ion O   0.980915522         0.047539909         0.451111470 1
ion O   0.980778809         0.047252240         0.139009400 1
ion C   0.647558804         0.380704217         0.252148887 1
ion C   0.314191211         0.714230246         0.338001009 1

The input file is:
include cell.lattice
include cell.ionpos
coulomb-interaction Slab 001
coulomb-truncation-embed 0.0  0.0  0.5 
ion-species SG15/$ID_ONCV_PBE.upf
elec-ex-corr gga-PBE
elec-cutoff 22
#core-overlap-check None
elec-smearing Fermi 0.01
kpoint-folding 12 12 1     #Metals need more k-points

dump-name cell.$VAR    #Filename pattern for saving outputs
dump End State          #Output State i.e. everything needed to resume the calculation

electronic-scf  \
	nIterations	400 \
	energyDiffThreshold	1e-14
ionic-minimize \
    nIterations 500 \
    energyDiffThreshold 1e-13 \ 
    knormThreshold 1e-7  #Threshold on RMS cartesian force  

Does this mean that I have to reconstructe my lattice? 
How should I do for this problem?

**Comment by shankar1729** [comment]
Yes, please update your structure definition to ensure that the third direction is exactly orthogonal to the first two. It appears that your input lattice started out that way, but optimization in another code led to slight mixing of the periodic and non-periodic directions, which is undesirable.

In this case, because you have such small non-zero off-diagonal entries in the third row and column of your lattice matrix, just set them to zero. Ionic optimization should fix the coordinates subsequently, and does not need an explicit transformation.

(If you had a situation where the truncated direction was much further from orthogonal, I would have recommended, switching the coordinates to Cartesian, picking a new third lattice direction which is exactly orthogonal, and then re-transforming the coordinates to fractional based on the new lattice.)

Best,
Shankar
