### ISSUE TITLE
Out of GPU memory

### ISSUE THREAD

**Issue by moyulyy** [shankar1729/jdftx#265]
Hi Shankar,

I installed jdftx on a device with 8 cores and an NVIDIA Tesla T4 GPU to try computing a 2D system with 120 atoms.

The program worked well during the initial "Allocating electronic variables" phase, but when beginning the calculation of "Electronic minimization" phase, "GPU memory allocation failed (out of memory)" is displayed, so that the computation stops.
I wonder if the problem is due to poor performance of the GUP hardware, or if the compilation and environment variables are not set properly.

By querying the Tesla T4 equipment information, its memory size for the 16 GB, through the tutorial https://jdftx.org/Customization.html, make JDFTX_MEMPOOL_SIZE = 12288 (12 GB, holds the memory for the most part).
/--------------------------------------------------
Run totals: 1 processes, 8 threads, 1 GPUs
Memory pool size: 12288 MB (per process)
nElectrons: 383.000000   nBands: 371   nStates: 4
/--------------------------------------------------

At compile time, use the command,
CC=gcc CXX=g++ cmake  -D EnableCUDA=yes \  
				-D CUDA_ARCH=compute_75\   
				-D CUDA_CODE=sm_75 \ 
				-D ForceFFTW=yes \ 
				-D EnableMKL=yes \
				-D MKL_PATH=/opt/intel/oneapi/mkl/2021.1.1 \ 
				../jdftx-1.6.0/jdftx

In the environment variable setting,
export MPICH_GPU_SUPPORT_ENABLED=1
export JDFTX_LAUNCH=""
export JDFTX_SUFFIX="_gpu"
export JDFTX_MEMPOOL_SIZE=12288

I was confused whether it was due to the larger computing system versus the smaller GPU performance, or whether it was due to poor setup or compilation.
I hope to get your opinions and suggestions on this issue.

Thank you for your efforts and look forward to your reply.

**Comment by shankar1729** [comment]
Your code compilation settings seem fine to me. Most likely, you are actually running out of GPU memory for this calculation. 

What is the number of basis elements reported during initialization? Please attach the complete log file so that we can pin this down more precisely.

Best,
Shankar

**Comment by moyulyy** [comment]
Attached is the output report, hoping to be helpful to this problem.
[Ion_opt.out.txt](https://github.com/shankar1729/jdftx/files/10416580/Ion_opt.out.txt)

Should this device be replaced with a GPU with more memory? Also, can I limit memory usage by setting some parameters to make the job complete (although at the expense of efficiency)?

**Comment by moyulyy** [comment]
Attached is the output report, hoping to be helpful to this problem.
[Ion_opt.out.txt](https://github.com/shankar1729/jdftx/files/10416580/Ion_opt.out.txt)

Should this device be replaced with a GPU with more memory? Also, can I limit memory usage by setting some parameters to make the job complete (although at the expense of efficiency)?

**Comment by shankar1729** [comment]
Based on your output file, the memory required to store one set of wavefunctions is nBands * nBasis * 16 bytes/k-point ~ 1 GB / k-point. A typical calculation needs to store 4 - 5 copies of wavefunctions concurrently for minimization / SCF, requiring ~ 5 GB / k-point with some margin. So this calculation would have fit easily with 4 GPUs using 1 k-point/GPU (MPI with 4 processes), but all k-points on a single GPU is definitely not expected to fit. 

So definitely, a GPU with more memory, or an array of GPUs to spread the k-points over would be helpful. Additionally, your specific GPU is not well-tested for double-precision computing, so it is unclear whether its performance would be substantially greater than a good CPU. (Many of the nVIDIA workstation / gaming GPUs are deliberately crippled in double precision performance so that you buy their more expensive compute devices.)

Best,
Shankar
