### ISSUE TITLE
DFT+U with SOC

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#266]
It seems that the strength of U for the f shell is underestimated in JDFTx when "spintype" is set to "spin-orbit". I have done DOS calculations of UC (uranium carbide) for the same values of U and J in JDFTx, Quantum Espresso and FPLO (the same pseudos were used in  JDFTx and QE). While the results are similar in QE and FPLO, the corresponding splittings in the f-shell due to U action appear to be smaller in JDFTx. Can you check this point?

**Comment by shankar1729** [comment]
JDFTx implements the simplified rotationally-invariant scheme by Dudarev et al. (see reported citation in code) with a single parameter U-J. Can you confirm that you are using the same scheme in QE and other codes?

Also, JDFTx only supports DFT+U on atomic orbitals, not on projectors which QE supports as an option. Please confirm that these settings are also the same.

Finally, is the issue happening specifically with SOC as mentioned in the issue title? Have you tested/please compare the results for the same system with non-spinorial PSPs to help isolate whether the issue is restricted to the spinorial case.

Thanks!
Best,
Shankar

**Comment by sergbuto** [comment]
QE does not allow to use the simplified U-J scheme in the case of SOC but the differences between JDFTx and QE results were significant on the energy scale and it is doubtful to me that the reason in the difference of the applied schemes. Furthermore, the FPLO scheme was also different from the QE's scheme used but results are similar.

In QE, DFT+U was also applied on atomic orbitals.

At the moment, I am busy with a number of projects and it will take quite some time before I can do more testing. The results I am talking about were obtained a while ago.

**Comment by sergbuto** [comment]
I forgot to mention that all the calculations were done for the non-spin polarized case.

**Comment by shankar1729** [comment]
Thanks: please post back with an MWE showcasing the error and expected results when you get a chance. That will help with finding the issue; it's going to be difficult for us to reproduce and identify the possible bugs without that.
