### ISSUE TITLE
How to improve computing speed and fixed potential 

### ISSUE THREAD

**Issue by fanfan0511** [shankar1729/jdftx#276]
Dear Shankar,

I tried to calculate fixed potential,I'm currently working on the first vacuum calculation,But it takes a long time. [](url)
It has been calculated for a week but the calculation has not been completed. The following is my input, output and configuration file. May I ask if some of my parameters were set incorrectly? Or is it just the way it is? Is there any way to improve the speed of calculation? Looking forward to your reply. Thank you very much.
[Calculation file.zip](https://github.com/shankar1729/jdftx/files/11540815/Calculation.file.zip)

**Comment by shankar1729** [comment]
You are running a calculation with nStates = 2 on 48 processes. This will lead to only 2 cores being used. See the [Getting Started](http://jdftx.org/GettingStarted.html) page for more details on this.

You seem to have 12 cores/node. So run with 2 processes, on eon each node, with 12 threads each. In SLURM, this would be `-n 2 -c 12` , and you can adapt this to other job submission systems / plain mpirun. 

Best,
Shankar

**Comment by fanfan0511** [comment]
Dear Shankar,
Thank you very much for your answer. I also want to confirm with you whether the input file parameters set are reasonable. Another question I would like to ask you is that the task will start from the beginning after I modify the submission file. I saw that setting initial-state parameter in the tutorial could make the calculation continue, but it could not continue after my test. There is no corresponding wave function shown in the output file. May I ask how I can correct this problem? Looking forward to your reply. Thank you very much
[Calculation file.zip](https://github.com/shankar1729/jdftx/files/11543800/Calculation.file.zip)

**Comment by shankar1729** [comment]
The calculation parameters seem fine to me, but you may want to consider using coulomb truncation in Slab mode as detailed in the Surface tutorials for better accuracy.

You should not specify `wavefunction lcao` if you want to use `initial-state`. Additionally, your calculation did not produce a wavefunction file because it did not reach the first time dump is initiated. If you want to checkpoint every few electronic steps, use `dump Electronic State` along with `dump-frequency Electronic 5`, e.g. to output every 5 SCF cycles / minimize steps.

Best,
Shankar

**Comment by shankar1729** [comment]
Please see the tutorials that talk about setting up geometries for molecules, slabs etc. You need to pick the embed center to be consistent with the atom positions you specified, so that periodicity is broken at the correct place. The error message you get is telling you that your current choice of the embed center is effectively slicing the unit cell too close to atoms.

You can get a quick estimate by fixing the geometry, but this will of course neglect charge and potential-dependent changes in adsorbate geometry than can be important in electrochemistry. That is one of the key needs for GC-DFT, so you may want to eventually update all the geometries self-consistently.

That's right: it is `dump-interval`, not `dump-frequency`. That part worked fine. Your subsequent run input has both initial-state and wavefunction commands. Drop the latter, if you want to use `initial-state`.

Best,
Shankar
