### ISSUE TITLE
Bound charge in solvated calculations

### ISSUE THREAD

**Issue by CaFa2** [shankar1729/jdftx#28]
Dear Shankar,

thank you very much for the fast response! I am testing the different solvation models for a slab of IrO2. I realized, just as in the tutorial on the oxide surface, that there is bound charge at the border of the unit cell, in a somewhat layered structure. I would have expected the bound charge to be primarily localized at the interface and to find homogeneously mixed charged regions in the bulk?
Another point is that for iso-surfaces (of the order of E-6 and smaller) there is bound charge in the region of the explicit system. I thought that the cavity is defined such as that the bound charge there is zero (no penetration of the liquid into the explicit system)?  
![slab_salsa](https://user-images.githubusercontent.com/39799080/40911325-d67dfe58-67ee-11e8-911f-3fd46f11c6c5.jpg)
![slab_candle](https://user-images.githubusercontent.com/39799080/40911351-e0d64392-67ee-11e8-8d91-29a2bb671078.jpg)

**Comment by shankar1729** [comment]
The first issue with bound charge is purely an output problem when you use Coulomb truncation in a system with a net dipole: the potential is calculated on the double size cell fine, but is discontinuous on the original size unit cell where the bound charge is calculated. This needs to be fixed by calculating the bound charge on the double size cell and then restricting to the original unit cell. Note that this does not affect the energies or chemical potentials in any way, and as a work around can be fixed simply by omitting those regions from your plot. (This error will always be confined to a few grid points from the plane of truncation.)

The bound charge at the 1e-6 level should also not be a problem: this is a consequence of the erfc shape function not having gone exactly to zero at the electron densities in the explicit system and happens most often for oxide-like systems with open bonding structures (rarer for metals). Which solvation model are you using? This should usually be less prevalent for the nonlocal cavity based models like SaLSA and CANDLE. Once again, this will not contribute to the physical observables.

Best,
Shankar

**Comment by CaFa2** [comment]
Dear Shankar,

thank you very much! I compared CANDLE, SaLSA and Classical DFT. 
In fact, what actually is the 'bound charge in the liquid' given in the .nbound file? Is it an induced ionic charge density of the liquid (like the difference between the homogeneous bulk liquid density and the actual liquid density induced by the explicit system) or is it the change of the electronic density of the explicit system induced by the liquid? In the first case, it would not be clear to me how PCM models with solvent electric response approximated by a continuum dielectric could give such a response? Is there are reference paper where I can find the definition of nbound?

**Comment by shankar1729** [comment]
It is the former: induced charge density in the liquid. In the code, it is calculated from the laplacian of the fluid contribution to the total electrostatic potential. (This potential can have a discontinuity on the unit cell boundary when using truncated Coulomb potentials which is the source of the undesirable features in the bound charge at the cell boundary.)

Shankar
