### ISSUE TITLE
The use of the label charged-defect

### ISSUE THREAD

**Issue by miaozhuang68** [shankar1729/jdftx#284]
Dear Shankar,
Thank you very much for your serious reply in the previous post. Now I can use most of the functions I need in JDFTx proficiently!
What I am currently calculating is the surface potential of the metal Slab. I need to deduct a part of the charge to simulate the polarization of the electrode. There is no doubt that I should use the label `elec-initial-charge` here.
But according to what you mentioned in [issue245](https://github.com/shankar1729/jdftx/issues/245) the Defect page in [jdftx.org](jdftx.org), my understanding is that if I want to place a charged defect in a relatively small area, I should use both tags `charged-defect` and `charged-defect-correction`. I don't know if I should use these two labels in my situation, if it will make my calculations more accurate, or is it enough to use `coulomb-interaction slab` and `elec-initial-charge`?
Looking forward to hearing from you, and thank you in advance for your answers!

Best,
Jam

**Comment by shankar1729** [comment]
For charging up a metal slab in the electrochemical context, i.e. with countercharge coming from an electrolyte, just follow the charged surfaces tutorials. No need for charged defect correction there.

You only need charged defect correction when you have localized charges due to defects, and your unit cell has a net charge. In the metal surfaces case for electrochemistry, the unit cell overall is neutral because your electrolyte countercharge neutralizes the electrode charge.

**Comment by miaozhuang68** [comment]
Dear Shankar,
thank you for your quick reply!
We used the `NELECT` label in our previous calculations in the vacuum in VASP, and some reviewers suggested that VASP would introduce a uniform background charge to keep the system electrically neutral. When the uniform background charge is large, the existing periodic background charge will interact with the uniform background charge and seriously affect the calculation.
I wonder if the implicit solvation model of JDFTx can handle the effect of uniform background charge well, because I urgently need to introduce a surface with a large electric polarization.
Best,
Jam

**Comment by shankar1729** [comment]
Implicit solvation models with an electrolyte will produce the compensating charge physically in the interface region (where the double layer should be). As long as you use fluid-cation and fluid-anion to specify an ionic concentration, as shown in all the tutorials involving charged systems, there will be no uniform background charge to deal with. (This is the whole point of the electrolyte solvation / GC-DFT work.)

Best,
Shankar

**Comment by miaozhuang68** [comment]
Dear Shankar,
This explanation helped me a lot!
The next thing I want to ask is when I want to get the potential of a charged electrode relative to the solution (not V_SHE, but V_solution), is using the `V_SHE(charged electrode)-PZC (vs. SHE) =V_solution` reliable? Because most of the potential changes are generated by Qnet.

**Comment by moyulyy** [comment]
Hi Shankar,

The ion concentration set in some literatures is 0.5M and 1.0M. How should I set the ion concentration?
In other words, how does the difference in ion concentration affect the energy calculation of GC-DFT.

Best,
lyy

**Comment by shankar1729** [comment]
See the documentation of commands fluid-cation and fluid-anion: the second parameter is the ionic concentration in mol/liter. For implicit solvation models, this changes the Debye screening length and the capacitance near PZC for nonlinear models, which in turn affects the charge at a given electrode potential in GC-DFT. However, effects like changes in explicit ion adsorption due to concentration cannot be captured by an implicit model. 

Best,
Shankar
