### ISSUE TITLE
No electronic calculations are performed

### ISSUE THREAD

**Issue by fanfan0511** [shankar1729/jdftx#289]
Dear Shankar,
I'm sorry to bother you again. I only iterated when performing potentiostatic calculation, but did not perform subsequent electron minimization calculation. May I ask why? In the compressed package are the calculation parameters I used.
[Ru.zip](https://github.com/shankar1729/jdftx/files/12138840/Ru.zip)

**Comment by shankar1729** [comment]
Please clarify your question: there are many inputs and log files in the attachment, and I'm not sure what you are asking.

**Comment by fanfan0511** [comment]
I'm sorry my question wasn't clear before. As shown in the figure, since the calculation under vacuum environment has not been completed (input file jdftx.in and output file jdftx.out), the solvation calculation in the next step is directly carried out (input file sol.in and output file sol.out). May I ask why?
![image](https://github.com/shankar1729/jdftx/assets/132865062/13aa3792-3ff4-44fc-b47f-63b1eb7fb62b)

**Comment by shankar1729** [comment]
Are you asking why the solvated calculation starts at all, because the vacuum calculation has not finished? That is because the code is capable of starting a solvated calculation from scratch too, running its own initial vacuum minimization. However, starting from a completed vacuum calculation is still recommended whenever practical.

Unrelated to your question, your calculation appears to be running very slowly. Please check the parallelization settings: you are running with 6 processes with only 2 nStates. Also, check if you have core binding issue: you may want to add `--bind-to none` to your mpirun command line. (See previous issues about these.)

**Comment by fanfan0511** [comment]
Yes, my question is why the vacuum computation is not finished and it stops at the place shown in the figure and will not be calculated, but the solvation calculation is carried out, which did not happen before, why is that?
Thank you very much for your question about parallel computing. I will modify it later.

**Comment by shankar1729** [comment]
Did the calculation fail at the indicated location, or time out on the job queue? If it failed, it could be an out of memory situation.
