### ISSUE TITLE
Problem with total and orbital projected density of states

### ISSUE THREAD

**Issue by gmarci** [shankar1729/jdftx#290]
Dear Shankar!

I ran into some problem with DOS and PDOS calculations in case of a single copper atom in vacuum. 

- I found, that when I sum up the orbital projected DOS (using OrthoOrbital option) I do not get the total version. For instance in DOS there is an extra peak in the non-occupied range, which misses from PDOS
- I also noticed, that the ratio of projected density of states for different orbitals is strange. For example, the HOMO of Cu contains contributions from both s- and d-type orbitals, but the amplitude of the latter one is at least 4 order of magnitude larger, the the former one.
Is there a kind of renormalization I miss?  

I attached the input and output files and also a figure about the DOS. I also tried the calculation without the Gaussian broadening (with default Esigma) and got similar results. 

Can you give me a hint, what is wrong with my computations?

Thank you in advance!

Best,
Márton

[input.txt](https://github.com/shankar1729/jdftx/files/12193160/input.txt)
[out.txt](https://github.com/shankar1729/jdftx/files/12193161/out.txt)
[dos_default_esgima.txt](https://github.com/shankar1729/jdftx/files/12193207/dos_default_esgima.txt)
[out_default_esgima.txt](https://github.com/shankar1729/jdftx/files/12193208/out_default_esgima.txt)
[input_default_esgima.txt](https://github.com/shankar1729/jdftx/files/12193209/input_default_esgima.txt)
[dos.txt](https://github.com/shankar1729/jdftx/files/12193162/dos.txt)
![DOS](https://github.com/shankar1729/jdftx/assets/37868770/2621c6f4-16fd-458e-9d84-24b237a1d48f)

**Comment by shankar1729** [comment]
Hi Márton,

1. The orthornormal orbitals are not complete, so the wavefunctions have contributions from the overall plane wave basis that are not in the orbitals. So you do not expect the projected DOS to add up to the total. (This is different from an atomic-orbital basis, where this will be artificially true.)
2. The "issue" is that the s and p orbitals you selected are the semi-core orbitals within the pseudopotential, rather than the valence ones. See the pseudopotential info pasted below: the first s and p orbitals correspond to 3s and 3p, which are much lower in energy than 3d. You probably wanted to use the "2s" and "2p" pseudo-orbitals in your dos specification, which would have corresponded to the second s and p, i.e. 4s and 4p real orbitals in this case.

```
    |300>  occupation: 2  eigenvalue: -5.020764
    |310>  occupation: 6  eigenvalue: -3.445588
    |320>  occupation: 8  eigenvalue: -0.925168
    |400>  occupation: 2  eigenvalue: -0.567638
    |410>  occupation: 0  eigenvalue: -0.326154
```

Your DOS may meet your expectations a bit closer on both points after switching to these orbitals. The ortho-orbitals still won't add up to the total exactly, but they will be quite a bit closer in this energy range where you expect these orbitals to dominate for the atom.

Best,
Shankar

**Comment by gmarci** [comment]
Dear Shankar!

Sorry for the late response! Thank you very much for your detailed explanation! 
I managed to compute the DOS and PDOS of the copper atom which are now comparable with the results provided by other programs (like GPAW).


Best,
Márton
