### ISSUE TITLE
Spin polarized calculations in JDFTx

### ISSUE THREAD

**Issue by DeanMSweeney** [shankar1729/jdftx#319]
Hello, 

I am using the JDFTx software for geometry relaxations and adsorption energy calculations on a variety of surfaces (Pd, Pt, Rh, and Ni). Due to the spin polarization required for Ni (z-spin), the run time is approximately tripling (even with appropriate nstates and cores). For example, a 3x3x5 Ni (111) clean slab is taking 30 hours of runtime. Do you have any recommendations/tricks for reducing run time for spin polarized calculations -- possibly running without spin polarized as an initial guess and then turning on? 

Thanks in advance!

**Comment by shankar1729** [comment]
Please post the log files for the spin-polarized example. The computational cost does go up by a factor of 2 for the additional spin channel, and could be increasing further due to slower convergence with the additional magnetization degree of freedom. However, those runtimes overall sound quite high, and I can check if your setup in the log is optimal.
