### ISSUE TITLE
Vacuum calculation of *NO failed at electronic minimization

### ISSUE THREAD

**Issue by Fangerrr** [shankar1729/jdftx#323]
Dear Shankar,
I am trying to compute the energy of NO adsorbed on the slab(CONTCAR from VASP). However, it failed at electronic minimization with stacktrace and error log generated. However, the calculation of hydrogen adsorption on the slab with the same setting is successful!  Could you please tell me what may be the cause for this? 
Looking forward to your reply!
[2NO.zip](https://github.com/shankar1729/jdftx/files/14973956/2NO.zip)

**Comment by shankar1729** [comment]
You seem to have three nitrogens duplicated in your inputs: the last three ones after Ga in your input also show up before, but with just the x coordinate wrapped under periodic boundaries. JDFTx did not complain about this because you have `core-overlap-check none`, but if you turn that off, it flags the problematic positions.

This is why you end up with a crazy-large positive energy in the LCAO, and eventually the run fails with some linear algebra error likely (not seen in the outputs for some reason). I'm actually surprised that the LCAO even managed to get that far.

Your runs should likely work fine after removing the duplicated atoms.

Best,
Shankar

**Comment by Fangerrr** [comment]
Dear Shankar,

Thanks for your professional help! The problem is solved and the job works fine now. 

Regards,

Qingchao Fang
