### ISSUE TITLE
cmake gives "Unsupported GNU Scientific Library version; need version >= 1.15" when GSL version 2.7 is installed

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#324]
It seems that however the flag for this is being set, it does not recognize GSL 2.7 as a valid version.

```
cbu@polaris-login-01:~/jdftx/build> cmake -D EnableCUDA=yes -D CudaAwareMPI=yes -D PinnedHostMemory=yes -D GSL_PATH=/home/cbu/gsl ../jdftx-1.7.0/jdftx
-- Cray Programming Environment 2.7.30 C
-- Cray Programming Environment 2.7.30 CXX
CMake Error at CMake-Modules/FindGSL.cmake:36 (message):
  Unsupported GNU Scientific Library version; need version >= 1.15
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/cbu/jdftx/build/CMakeFiles/CMakeOutput.log".
See also "/home/cbu/jdftx/build/CMakeFiles/CMakeError.log".
cbu@polaris-login-01:~/jdftx/build> clear
cbu@polaris-login-01:~/jdftx/build> cmake -D EnableCUDA=yes -D CudaAwareMPI=yes -D PinnedHostMemory=yes -D GSL_PATH=/home/cbu/gsl ../jdftx-1.7.0/jdftx
-- Cray Programming Environment 2.7.30 C
-- Cray Programming Environment 2.7.30 CXX
CMake Error at CMake-Modules/FindGSL.cmake:36 (message):
  Unsupported GNU Scientific Library version; need version >= 1.15
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/cbu/jdftx/build/CMakeFiles/CMakeOutput.log".
See also "/home/cbu/jdftx/build/CMakeFiles/CMakeError.log".
cbu@polaris-login-01:~/jdftx/build>
```

**Comment by ColinBundschu** [comment]
This is a problem with the release 1.7, but not on the github version. Given that release 1.7 is the newest release and that the default version of GSL is 2.7, it may be worth hot fixing this.

**Comment by shankar1729** [comment]
I tested building the 1.7.0 release code with GSL 2.7 and did not encounter any issues. I also checked that I have not made any changes to the build system to address GSL versions since v1.7.0.

I notice that you have the GSL_PATH in your cmake command line set to the jdftx source directory: is this a typo / did you install the dependencies within the source path? If the latter, this could be a path conflict issue of some sort. Also, make sure you cleaned out the build directory completely between tries if you had an error in the path initially and you fixed it later. (CMake remembers many errors from previous builds if CMakeCache.txt remains in particular.)

Best,
Shankar

**Comment by ColinBundschu** [comment]
I am not sure I understand your comment about the `GSL_PATH`. Its set to `/home/cbu/gsl` above, which is not the jdftx source directory. I did `rm -rf *` on the build directory and the issue persists.

**Comment by shankar1729** [comment]
Sorry, I must have misread the cmake line before. Can you post the contents of the /home/cbu/gsl directory? I suspect that it's not finding the required files there, and looking at an older system gsl instead. So I'm wondering if the error is not that GSL 2.7 is not supported (it certainly is), but rather that it's not finding your GSL 2.7 due to some path issue.

**Comment by ColinBundschu** [comment]
```
cbu@polaris-login-01:~> ls /home/cbu/gsl
bin  include  lib  share
cbu@polaris-login-01:~>
```

**Comment by shankar1729** [comment]
Can you do a find on that directory instead so that we can see the contents within as well?

**Comment by shankar1729** [comment]
This issue is now redundant given the several subsequent threads fixing compilation with nvhpc.
