### ISSUE TITLE
The constant potential structure optimization encountered an error during continuation calculation.

### ISSUE THREAD

**Issue by hy19934567** [shankar1729/jdftx#325]
Dear Shankar,

I'm new to using jDFTx and currently working on structure optimization under constant potential. I have encountered two issues that I need help with.

Firstly, I'm unsure if my input settings are correct and if the calculation speed is normal. The calculation didn't converge within 24 hours. Are there any settings I can adjust to speed up the calculation? I have attached the input and output files in the zipped folder named "step1".
[step1.zip](https://github.com/shankar1729/jdftx/files/15249485/step1.zip)

Secondly, I encountered an error when attempting to continue the calculation based on the output files generated from the step1:
"Coulomb truncation embedding center is not invariant under symmetry matrix:
[  -1   0   0  ]
[   0   1   0  ]
[   0   0  -1  ]
[  0  0  0  ]
Coulomb truncation embedding center is not invariant under symmetries."
The input and output files for this step are attached in the zipped folder named "step2". Could you please provide some suggestions to resolve this issue?
[step2.zip](https://github.com/shankar1729/jdftx/files/15249488/step2.zip)

Thank you very much for your time.

Best regards,
Yun Han

**Comment by shankar1729** [comment]
Hi Yun,

For the speed part, please look at the getting started page and the numerous discussions before on MPI versus threads parallelization depending on the number of reduced k-points, nStates. Essentially, right now only 1 of 64 processes is doing the work in your calculation since you have nStates = 1.

In the second step input, you forgot to include the ionic positions. Without them, the code picked up a higher symmetries from lattice + (no) basis, which is then violated by the coulomb truncation center. Once you fix the input and include the ions, you won't have that symmetry any more and your current truncation center is fine.

Best,
Shankar

**Comment by hy19934567** [comment]
Dear Shankar,

Thank you for your prompt response.

Unfortunately, I encountered another error after including the ionic positions.  The details are provided in the "Neutral_n1c128.out" as attached):
"Encountered 60 errors while parsing input:
Command 'ion'  with command line:
        ion C   0.999127328         0.000367513         0.240160510   1
failed with message:
        Species C has not been defined"

The settings of the keyword "ion" are same as I've been using before, and I haven't encountered this error before. I have reviewed the infut setting, but I counldn't find anything inapppropriate. Could you please check the input files and help me figure out the problem?
[n1c128.zip](https://github.com/shankar1729/jdftx/files/15258002/n1c128.zip)


Thank you very much for your time and assistance.

Best
Yun

**Comment by shankar1729** [comment]
You must not have included the ion species command then. Please go through the tutorials to get comfortable with the input file setup.

Best,
Shankar
