### ISSUE TITLE
Feature request: Forces based convergence

### ISSUE THREAD

**Issue by ColinBundschu** [shankar1729/jdftx#328]
In addition to the standard convergence criteria, would it be possible to specify a threshold for the maximum allowable amount of force on a single atom during ionic relaxation?

**Comment by shankar1729** [comment]
This was already added recently for BEAST-DB production calculations: add `maxThreshold yes` to `ionic-minimize` or `lattice-minimize`, which will switch the reported grad_K to grad_max. The value of knormThreshold then gets applied to max force instead of rms.  (I haven't yet updated the web docs: I will do this with a new release that's overdue at this point.)

**Comment by shankar1729** [comment]
Please confirm if the existing code works correctly for your use case and close this issue. The documentation is now updated on https://jdftx.org/CommandIonicMinimize.html (see flag `maxThreshold`).

**Comment by ColinBundschu** [comment]
Can you clarify the units on `knormThreshold`?

**Comment by ColinBundschu** [comment]
And for convergence is it logical AND with the energy difference between steps or logical OR?

**Comment by shankar1729** [comment]
OR; it will stop when any of the convergence criteria are satisfied.

**Comment by ColinBundschu** [comment]
Is there any way to make it AND? I would like both the energy to be relatively constant and the forces to be small. Having one but not the other is undesirable.

**Comment by shankar1729** [comment]
Support added now with new option "convergeAll" in every minimize command with commit abd55369

**Comment by ColinBundschu** [comment]
Thank you!
