### ISSUE TITLE
cmake doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [shankar1729/jdftx#36]
It has built executables: ```jdftx```, ```phonon```, ```wannier```, and shared lib ```libjdftx.so```.
How can I know what should be installed?

**Comment by shankar1729** [comment]
Hi Yuri,

We don't have an install target at the moment, and recommend using the executables directly from the build directory as outlined in the tutorials. If you need to set up a clean install directory, the best way at the moment is to initiate cmake directly in the final path you wish to use, and after the build, remove the cmake* (case-insensitive) files and directories.

Best,
Shankar

**Comment by yurivict** [comment]
Hi Shankar,

I've created the FreeBSD port for jdftx, and wasn't sure which files should be installed.

So I installed:
```
	/usr/local/bin/jdftx
	/usr/local/bin/phonon
	/usr/local/bin/wannier
	/usr/local/lib/libjdftx.so
	/usr/local/share/jdftx/pseudopotentials/GBRV/ag_lda_v1.4.uspp
	/usr/local/share/jdftx/pseudopotentials/GBRV/ag_lda_v1.uspp
        /usr/local/share/jdftx/pseudopotentials/GBRV/ag_pbe_v1.uspp
        /usr/local/share/jdftx/pseudopotentials/ {all other pseudopotentials}
```

I am not sure if it is able to find pseudopotentials in this location.

**Comment by shankar1729** [comment]
Hi Yuri,

Indeed, that was the correct specification, but pseudopotential detection would not have worked.

Since this was one of my long-time to-do's anyway, I have added the install target in the latest commit on git. Please note that if you want to relocate the install, use CMAKE_INSTALL_PREFIX during configuration and not the DESTDIR mechanism during make install.

The pseudopotential loader adds support for installed locations now. The loader will check current directory, build directory and then install directory for the psps, so you may still see it getting loaded from the build directory if present.

Thank you for putting together a port, please let me know how that works out!

Best,
Shankar

**Comment by yurivict** [comment]
It works fine.
Thank you for implementing the 'install' target!
I've updated the port.
