### ISSUE TITLE
phonons in hBN

### ISSUE THREAD

**Issue by ciccarino** [shankar1729/jdftx#41]
Hi Shankar,

I've been trying to model some defects in hBN and I've run into some issues which I haven't been able to figure out. I am able to avoid imaginary frequencies in all instances of using a supercell of defect-free hBN. Then, upon introducing the defect and performing an ionic-minimization, the phonon calculations generates some troubling results. The results are attached for the C<sub>B</sub>V<sub>N</sub> defect. Some general trends I found:

* The imaginary frequencies showed up for both the bulk and monolayer calculations. I was thinking maybe there was something going on with the Grimme van der Waals correction, but I don't use that in the monolayer.
*  I was able to get exactly the same imaginary frequencies using electronic-minimize and electronic-scf for the select cases where I tested this.
* This was a widespread outcome across 6+ defects studied in bulk, monolayer and bilayer hBN. There appeared to be this rouge unstable mode between ~ 50 and 100 meV below zero, despite the defect-free cells showing no issue.
* I wouldn't think cell size is the issue. The monolayer is on a 6 6 1 grid of monolayer hBN cells, and the bulk is modeled using a 5 5 2 grid of bulk hBN unit cells. 

Do you have any thoughts on this? I'm a bit puzzled by these outcomes. As always, thank you very much for your help. 

Regards,
Chris

[phonons-hBN.zip](https://github.com/shankar1729/jdftx/files/2489918/phonons-hBN.zip)

**Comment by shankar1729** [comment]
Hi Chris,

This issue is most likely because your defect breaks hexagonal symmetry, while your lattice is still hexagonal. That strong imaginary mode likely corresponds to the symmetry breaking distortion of the lattice.

If you tried the same for a C_B defect which still retains three-fold rotation symmetry, you may not have this problem. For C_B V_N, you need to do a lattice minimization to account for the symmetry breaking distortion.

Best,
Shankar
