### ISSUE TITLE
How to force continuing lattice-minimize with old wfns after stopping program or crash?

### ISSUE THREAD

**Issue by ximik69** [shankar1729/jdftx#48]
Hi dear, Shankar.

I often need to stop jdftx_gpu with lattice-minimize, because I need to pack my notebook and bring it home/in my office. Thus I need to shutdown or suspend it. CUDA apps either crash or freeze system during suspend completely. Thus I need stop jdftx_gpu.

Is there any way to continue lattice-minimize using old wfns after stopping program?

Some objects take several hours for initial elec-minimize and converge much faster after that.
Another possible usage is stopping JDFTx to adjust some parameters, not related to wavefunctions/kpoint-folding/spin-type directly, with subsequent reuse of  old wfns.
Then I can rerun lattice-minimize from scratch, say two times , for converging to best results with stress less than 1e-5.

Best wishes,
Igor.

**Comment by shankar1729** [comment]
At the moment, this is not possible due to the basis-set change during lattice-minimize. This might be possible in the next major release with a different-format wavefunction that bundles the G-vectors with the wfns.

You could use real space wfns with a manually specified fft-box, but I wouldn't recommend it due to the much higher disk space requirements.

Best,
Shankar
