### ISSUE TITLE
Does two-dimensional material(fixed-potential)calculation needs geometry optimization?

### ISSUE THREAD

**Issue by Wangfeiteng1** [shankar1729/jdftx#50]
Dear all,
I 'm  going to do a fixed-potential calculation. In the tutorial, the structure of Pt slab model is fixed. Now I am about to study a single layer graphene. In fixed-charge calculation(from other codes instead of JDFTx), I have to optimize the structure, because two-dimensional structure could vary under different charge state. How about geometry optimization at constant potential calculation? Do I have to do target-mu+ionic minimize both? This seems to be very time-consuming. Could any one give me some suggestions?Thank you!

Best Regards!

Wolffett

**Comment by shankar1729** [comment]
Hi Wolffett,

You would need to do ionic minimize and target-mu in general. Make sure you start from an optimized geometry for the neutral calculation, and if you are doing a whole series of potential calculations, initialize each mu calculation from a neraby mu you have already finished. This should speed up the scans over potentials.

Additionally, have you looked through the other threads here regarding performance and the getting started page on parallelization? The most common complaints of speed with jdftx often arise due to sub-optimal MPI run configuration.

Best,
Shankar

**Comment by Wangfeiteng1** [comment]
Hi, Shankar,

 Thank you for your reply.

Best,
Wolffett

**Comment by Wangfeiteng1** [comment]
Hi, Shankar,

Sorry to bother you again. I have a N2 molecule adsorbed on a specific site of the slab. Then, I add a H atom to the N2 molecule. Could you please tell me if I can do partial Hessian analysis in your codes? I just want to know the energy difference and the Hessian analysis of the slab is not necessary. 
Thank you in advance!

Best,
Woffett

**Comment by shankar1729** [comment]
If you use the vibrations module with the flag useConstraints, then it won;t move the atoms with moveScale = 0. This should do something similar to the partial Hessian analysis.

**Comment by Wangfeiteng1** [comment]
Hi, Shankar,

Thank you very much for your reply. Recently I was calculating the NRR(Nitrogen Reduction Reaction) on a 2-D material at fixed potential. I did the calculation according to the literature "Substantial Impact of Charge on Electrochemical Reactions of Two-Dimensional Materials". The formulation is as following    
deltaGcpm= Gsol(H*Q2)-Gsol(*Q1)-0.5*G(H2(g))+|e|U-(Q1-Q2)mu
I adjusted the system to a certain potential and optimized the structure. My results are as follows
Gsol(N2)=-465.1306757
Gsol(N2H)=-465.523755
Q1=-1.7463,Q2=-1.99435,mu=-0.19183,G(H2(g))=-1.15555,U=-0.56(relative to standards USHE=-4.66)
The resulted reaction free energy is too positive to be trusted.Could you please give me any suggestion?Why the result would be in this way? I also tested it by fix the potential to -0.15067,the result free energy change is also too positive. 
Your any suggestions would be appreciated!

Best,
Woffett

**Comment by shankar1729** [comment]
Hi Woffett,

I suspect that you are not balancing the number of electrons carefully. What was the result, how positive is too positive?

Please specify the reaction more clearly and elaborate on what calculations you are doing for each of the cases. 

Best,
Shankar

**Comment by Wangfeiteng1** [comment]
Hi, Shankar,
Below is my input file
include  Ru1C2N1.lattice
include  Ru1C2N1.ionpos

ion-species GBRV/$ID_pbe.uspp
elec-cutoff 20 100

coulomb-interaction Slab 001
coulomb-truncation-embed 0 0 0

kpoint-folding 4 4 1
elec-smearing Fermi 0.01

spintype z-spin
van-der-waals

electronic-minimize nIterations 200
target-mu -0.19183

fluid LinearPCM
pcm-variant CANDLE
fluid-solvent H2O
fluid-cation Na+ 1.
fluid-anion F- 1.

ionic-minimize \
    nIterations 100 \
    energyDiffThreshold 1e-6 \
    knormThreshold 1e-4  #Threshold on RMS cartesian force

dump-name Ru1C2N1.$VAR      #This will overwrite outputs from successive runs
initial-state Ru1C2N1.$VAR  #This will initialize from the preceding calculation
dump End State BoundCharge
The reaction is 
*N2+H+ + e-  ---> *N2H (here * denotes the catalyst site which N2 and N2H adsorbed on)
I optimized the *N2 and *N2H structures with the input parameter as above shows. Finally I get the grand canonical free energy G. Below are the results
Gsol(N2)=-465.1306757Ha
Gsol(N2H)=-465.523755Ha
Q1=-1.7463,Q2=-1.99435,
mu=-0.19183Ha,U=-0.56eV(relative to standards USHE=-4.66)
G(H2(g))=-1.15555Ha,
The I calculated the reaction energy of the reaction:*N2+H+ + e-  ---> *N2H according to the formula 
deltaGcpm= Gsol(N2H*Q2)-Gsol(*N2Q1)-0.5G(H2(g))+|e|U-(Q1-Q2)mu
I get deltaGcpm=3.171038336eV. This value is too positive for a reaction to occur.
I'm not so good at setting the parameter, Could you give me any suggestions?
Thank you for your patience and explaination!

Best,
Woffett

**Comment by shankar1729** [comment]
Your issue is probably in the energy difference calculation, specifically
the +|e|U-(Q1-Q2)mu term. When using the grand canonical energies Gsol, the
mu*N terms for the two surface-adsorbed species are already included. You
only need to convert the hydrogen to the same form. So the formula should
just be:

*    deltaGcpm= Gsol(N2H*Q2) - Gsol(*N2Q1) - Gsol(H+)

where Gsol(H+) is the grand free energy at the same mu. Further, Gsol(H+)
does not change with electron mu as it has no electrons, and Gsol(H+) =
(1/2) G(H2(g)) at SHE conditions, which implies Gsol(H+) = (1/2) A(H2(g)) -
muSHE, where A(H2(g)) is the Helmholtz free energy per H2 molecule at
standard conditions (must include gas phase entropy etc. from thermo tables
/ ideal gas law in addition to ground state energy calculation in DFT).
Therefore your net result will be

    Gsol(H+) = *Gsol(N2H*Q2) - Gsol(*N2Q1) - (1/2) A(H2(g)) + muSHE

Best,
Shankar

**Comment by Wangfeiteng1** [comment]
Hi Shankar,

Thank you very very much! 
You said that  Gsol(H+) = (1/2) A(H2(g)) -muSHE because H+ has no electrons, Then what if I have a molecule with electrons, for example, Gsol(N2).Does that means  Gsol(N2) =  A(N2(g)) -muSHE is not suitable and we should calculate Gsol(N2) by doing a fixed-potential task ? Is it meaningful to do fixed-potential calculation for an isolated N2 molecule? 
Thank you for your patience and explaination!

Best,
Woffett

**Comment by shankar1729** [comment]
For any molecule reacting in gas form, calculate the total energy of an isolated molecule, and from it the helmholtz free energy using ideal gas / Thermo tables. Convert it to Grand free energy by subtracting mu*N, where N is the number of valence electrons in the molecule DFT calculation.

Please see our JCP paper on Grand canonical DFT, in the final section containing the UPD example. These points are discussed in detail there.

Best,
Shankar
