### ISSUE TITLE
About the output of jdftx:lcao minimize Iter has a lot of bad information.

### ISSUE THREAD

**Issue by zhangnn1996** [shankar1729/jdftx#63]
Hi Shanker,
when I run jdftx software, in output file ,it write:

LCAOMinimize:   Wrong curvature in test step, increasing alphaT to 3.194499e-01.
LCAOMinimize:   Bad step direction: g.d > 0.
LCAOMinimize:   Step failed: resetting search direction.

Do I need to pay attention to these information?
![image](https://user-images.githubusercontent.com/53133202/61586764-22527800-abae-11e9-8a21-e6df1000ebd1.png)

In addition ,I'm doing a work on graphene, I'm confused about the parameter coulomb-truncation-embed. I want to know if there is a adsorbed molecule, if the parameter is still set to the position of graphene ,or it is set to the middle of the graphene and the adsorbate.

Thank you very much!

**Comment by shankar1729** [comment]
LCAO can initially have some difficulty in getting to a smooth portion of the energy landscape. So it can have a few bad steps initially, but should eventually find it's way to good steps.

Your input looks fine overall from what I could see. You may want to use a higher smearing or more k points; that may make things easier to converge.

Make sure your atoms are well within the unit cell centered on your truncation center. There is no need to set the truncation center exactly at the geometrical center of your system, but you would want it to be somewhere close to it to have the most efficient (smallest) unit cell. For small adsorbates, I would typically center on the slab and just leave extra room rather than change the center each time. (There is no single correct choice here.)

**Comment by zhangnn1996** [comment]
I'm sorry but you mean I should also change the x and y corrdinate to the center of graphene surface ? (not just change z to the slab position ) ,which means I should set :
coulomb-truncation-embed 0.48 0.52  0.25

In addition, as you mentioned , I set the gauss smearing to 0.003675  to be consistent with the parameter in VASP in which I set SIGMA to 0.1. I'm confused with the smear method. In my opinion, Use fermi smear  if it's metal ,use gauss if it's semiconductor or insulator . Is it right? What will happen if I set fermi smear on a semiconductor system ?Does it impact much?(or it just slow down the convergence)

The last question is  about the parameter "kpoint" . kpoint 0 0 0  1 means the weight of K point .So can I copy the value of IBZKPT in VASP here ? Or I don't need to set this parameter and the program will calculate it based on "kpoint-folding" ?

Thanks very much!

**Comment by shankar1729** [comment]
Only z matters in slab mode of truncation. In isolated mode, all coordinates of center matter.

You'll need smearing for graphene. Gauss or Fermi don't matter as much. For best convergence in semiconductor, don't use smearing.

I'm not familiar with the vasp commands. Kpoint sets the reference k point with weight, while folding makes a mesh out of it in the standard way. Use 0 in each periodic direction for gamma centered mesh, and 0.5 for offset mesh. See the tutorials and the command docs.
