### ISSUE TITLE
jdftx installation error

### ISSUE THREAD

**Issue by AlphaKnight999** [shankar1729/jdftx#65]
[Viren@localhost build]$ cmake -D EnableMKL=yes ../jdftx-1.4.2/jdftx

-- Found GSL: /usr/local/lib/libgsl.so
-- Found MKL: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;gomp
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindMPI.cmake:587 (find_package_handle_standard_args)
  CMakeLists.txt:94 (find_package)

can anyone help with this cmake error

**Comment by shankar1729** [comment]
Do you have the MPI packages installed, and in a standard path? Are mpirun, mpicxx etc. in path? If not, you will need to modify environment variables to expose the MPI executables.

You can also choose to compile without MPI by adding -D EnableMPI=no, but that is probably not what you want.

Best,
Shankar

**Comment by AlphaKnight999** [comment]
We have installed Parallel Studio. How do we modify the environmental variables .

**Comment by shankar1729** [comment]
Please see 
https://software.intel.com/en-us/articles/setting-up-the-build-environment-for-using-intel-c-or-fortran-compilers for instructions on your specific version of parallel studio and platform. Make sure you run cmake for jdftx in the same shell for those variables to persist (since those instructions only seem to set variables for current session).
