### ISSUE TITLE
Fix potential calculations confusion

### ISSUE THREAD

**Issue by Yanhuanjin** [shankar1729/jdftx#67]
Hi Shankar,

I did a fix potential calculation based on my VASP structure results, it was about a Volmer reaction related to one electron transfer, like (H+ + e- => H*). The H was surround by explicit H2O molecules. However, when the potential is changed larger than 2 eV (from -0.1167 Hartree to -0.1984 Hartree) , the free energy between initial state(IS) and final state(FS) only changed less than 1 eV (0.78 eV).  However, I thought it should be larger, at least be closed to 2 eV. Did my calculations go wrong or was that the way they were?

Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

The grand free energy of each system, G, should vary approximately linearly with mu with a slope of -N (where N is the number of valence electrons in the calculation), provided the charge state doesn't change in the range of interest. The deviation from linearity will depend on how much the charge state changes with potential.

I am not exactly clear what quantity you are comparing to the change in mu. Are you comparing the change in free-energy-difference of the reaction? How do you distinguish between H+ and H* in a fixed-potential case where the charge state is automatic? Are you effectively just measuring a difference in grand free energy of two different geometries of a hydrated H cluster because your initial VASP geometries are different for the H+ and H*? (If you ionically optimized, H+ and H* will both end up at some charge state, perhaps in between the two, which is the equilibrium at the chosen potential.)

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi Shankar,

>  Are you comparing the change in free-energy-difference of the reaction? How do you distinguish between H+ and H* in a fixed-potential case where the charge state is automatic? Are you effectively just measuring a difference in grand free energy of two different geometries of a hydrated H cluster because your initial VASP geometries are different for the H+ and H*?

Thank you for your reply.

Yes, I wanted to distinguish H+ and H*, yet I don't know what charge states they are.
In fact, I want to know how a reaction barrier would change by applying different potentials. You know, in experiments, some reaction could not be achieved, but could be achieved by increasing the voltage to a certain value. Hence, the reaction barrier can be considered to be 0 at this certain potential. I want to get this potential value by doing fix potential calculations. However, just as you said, the charge states of H+ and H* are automaticlly adjusted. That is the problem. Under the potential value that lower the barrier to 0, H+(H*) is not H+(H*) anymore? Is this the right potential that I want?

Best,
Daniel

**Comment by shankar1729** [comment]
Hi Daniel,

It is fundamentally not possible to distinguish H+ and H* _in equilibrium_ at fixed potential, because they are two specific charge states that are in equilibrium at different potentials. If you are trying to calculate an electron transfer barrier, that requires a completely different methodology entirely.

The key assumption in fixed electron potential calculations of reaction mechanisms are that electron transfers are happening very quickly on the time scale of the reaction, so that electron numbers are in equilibrium with the electrode potential. This is often the correct regime at an electrochemical interface, but may not be appropriate at all for homogeneous solution or gas-phase electron transfers. (You will probably need constrained DFT + Marcus theory for calculating those.)

Best,
Shankar

**Comment by Yanhuanjin** [comment]
Hi, Shankar,

Thank you for your reply. It helps me a lot.

Best,
Daniel
