### ISSUE TITLE
LCAO minimisation error

### ISSUE THREAD

**Issue by jayuw** [shankar1729/jdftx#68]
Dear Shankar,

I encountered this error:
LCAOMinimize: Iter:   0  Etot: +58246.1371311515758862  |grad|_K:  9.265e-03  alpha:  1.000e+00
LCAOMinimize:   Test step failed with Etot = -nan, reducing alphaT to 1.000000e-01.
LCAOMinimize:   Test step failed with Etot = -nan, reducing alphaT to 1.000000e-02.
LCAOMinimize:   Test step failed with Etot = -nan, reducing alphaT to 1.000000e-03.
~

Could you please give me some advice on what should I do?

**Comment by abhiShandy** [comment]
Hey Jay,
`Etot: +58246.1371311515758862` indicates unstable ionic configuration. Please check ionic positions.

You should also check the units of ionic positions, and whether the [coords-type](http://jdftx.org/CommandCoordsType.html) matches the convention used for ionic positions.

**Comment by jayuw** [comment]
Dear Abhi,

Thanks for your reply.
I have optimised my structure using VASP, and use it as an input in JDFTx. I used coords-type cartesian. Do you have any other possible reason for this error?

**Comment by shankar1729** [comment]
I second Abhishek's suggestion that this is most likely a geometry issue. Run the createXSF script distributed with jdftx on your output file, visualize that xsf using vesta or xcrysden, and check whether the geometry interpreted by JDFTx is what you think it is. Common geometry errors when converting from VASP include specifying cartesian coordinates in Angstroms instead of bohrs, and putting the lattice vectors in rows instead of columns.

If you can verify that all of this is correct, then perhaps post your output file so that we have more information to help with.

Best,
Shankar

**Comment by jayuw** [comment]
Dear Shankar and Abishek,

Please find attached the output file on my calculation. I believe that the geometry is correct, and I have also checked using createXSF script and visualise it in Vesta. Could you please help me what is wrong with my parameters?

Regards,
Jay

[Neutral.txt](https://github.com/shankar1729/jdftx/files/3480006/Neutral.txt)

**Comment by shankar1729** [comment]
Hi Jay,

Indeed, your structure appears to be correct. I took the input commands out of your attached log file and ran it on my computer, but it did not give the high initial energies and LCAO convergence issues you indicated above. Could there be an issue in your compilation perhaps? Do other examples, say from the tutorials, produce the expected results? Perhaps, also update your code to the latest release to see if this is emerging from an older bug?

Also unrelated to the issue above, I noticed two problems in your input: 

1. The CANDLE solvation model is not parametrized for EC (only water and acetonitrile). You should use the GLSSA13 variant, otherwise CANDLE will proceed with water parameters (there will be a warning in the output file about this).

2. You may want to check your parallelization strategy: with nStates = 13, you should target number of MPI processes accordingly. 3 processes would have been wasted in your run. Read the getting started page for more info on selecting number of processes.

Best,
Shankar

**Comment by jayuw** [comment]
Thanks for your reply and advice. I will check more, so far the compilation looks good.
