### ISSUE TITLE
Tutorial - Fixed-potential calculations 

### ISSUE THREAD

**Issue by khyeoh** [shankar1729/jdftx#92]
Dear Dr. Shankar,

In the tutorial for Fixed-potential calculations, we can  plot the extracted results using gnuplot. The last line of the gnuplot script is given as: 

plot "mu_N.dat" u ((mu0-$1)*27.2114):(($2-N0)*qe/A) w l

Subsequently, we can plot the graph where the x-axis is labelled as "V - PZC". Shouldn't it be "PZC-V" since in the gnuplot script, the command is written as:

plot "mu_N.dat" u ((**mu0-$1**)*27.2114):(($2-N0)*qe/A) w l

instead of

plot "mu_N.dat" u ((**$1-mu0**)*27.2114):(($2-N0)*qe/A) w l

Thanks!

Yeoh

**Comment by shankar1729** [comment]
Hi Yeoh,

The original equation is correct because of the negative electron charge. The electron chemical potential corresponds to the *potential energy* of the electron, while the electrode potential corresponds to the electrostatic potential, which differ by a factor of -e. 

Note the electrostatic potentials output by JDFTx (eg. d_tot) are also effectively potential energy profiles, or alternately you can think of it as using an electron-is-positive sign convention for the charge internally. Regardless, you need to introduce the negative sign to connect to experimental convention.

Best,
Shankar

**Comment by khyeoh** [comment]
Dear Dr Shankar,

Thank you very much !
